### ISSUE TITLE
LP Token names get blended across AMMs

### ISSUE THREAD

**Issue by wengzilla** [hodgerpodger/staketaxcsv#103]
When you LP token pairs across AMMs you will experience naming collisions. For instance, if you LP LUNA and UST on Loop DEX and LUNA and UST on Astroport, both tokens will be called LP_LUNA_UST, but the number of tokens you receive can be dramatically different. Therefore, cost basis accounting gets messed up upon deposit / withdrawal.

I think the fix is to key the name of the token by AMM, however, this will result in secondary impacts (e.g., Koinly NULL mapping limitations).

**Comment by Mylros** [comment]
Agreed. What I have been doing is naming TS_Token1_Token2 for Terraswap, AP for Astroport, and LO for Loop.
Tax software providers are very limited right now for this kind of Defi transactions.

**Comment by hodgerpodger** [comment]
Just removing issues for which action unlikely to be taken.  Re-add if desired.
