### ISSUE TITLE
Mirror limit orders not quite working...

### ISSUE THREAD

**Issue by wengzilla** [hodgerpodger/staketaxcsv#112]
The traditional swap function pulls the first msg, but doesn't realize there is a second msg that reflects the true cost.

https://finder.extraterrestrial.money/mainnet/tx/FA2B1898447CDB3048237D3F29F340D68B1B5C328A5C8D849007B5BABF98098C

In this transaction, the cost should be $536.500000 and NOT $535.590842. Small difference for this trade, but as trades get larger O(10K) or O(100K), the difference is really large.

@hodgerpodger what's the best way to get around this issue?

**Comment by hodgerpodger** [comment]
Something to the effect of _handle_execute_order_if_exists() at top of handle_swap() in col4.handle_swap.py?
  * intention being "execute_order" should supersede if exists

I'm guessing it's way easier to add to logic of col4.handle_swap than to try to rebuild logic into col5.*.


This is just a guess--feel free to make judgment here.   I have tests for a number of swaps so don't let compatibility worry you too much.

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/8288538da42f2451beed38d684c063d881e4d9f4.

Reopen if continued or similar problems.
