### ISSUE TITLE
ORION tokens are incorrectly handled 

### ISSUE THREAD

**Issue by laine-ust** [hodgerpodger/staketaxcsv#119]
Orion and a few other tokens on Terra are registered with another decimal base than native terra denoms. Most use 6 digits (divide by 1M) however Orion being cross chain is registered with 8 digits, thus divide by 100M.
I belive the same applies to XDEFI, but I don't have their token address handy.

Orion token:
https://finder.extraterrestrial.money/mainnet/contracts/terra1mddcdx0ujx89f38gu7zspk2r2ffdl5enyz2u03

I can share Txes via email.

Issue seen so far on 
- airdrop claims 
- LP provide / withdraw

**Comment by hodgerpodger** [comment]
I think I fixed this just yesterday by clearing db cache in prod (which I failed to do eons ago).  Let me know if you still see the issue on any new CSVs on stake.tax (and can email the tx, which would help).

**Comment by hodgerpodger** [comment]
I believe this is fixed now but please do reopen if continued issues.  Better to close now and reopen later, so that action would be taken.

**Comment by laine-ust** [comment]
Sorry for the late reply!
It does indeed work, just tested locally with the latest version.
Thanks :)
