### ISSUE TITLE
Costs for failed transactions on Osmosis are not accounted for

### ISSUE THREAD

**Issue by OnTheHedge** [hodgerpodger/staketaxcsv#124]
Non-zero fee costs for failed transactions on Osmosis are not picked up by the stake.tax app. Here is an example of a failed redelegation which had a non-zero fee, but which is not picked up by the app:
https://www.mintscan.io/osmosis/txs/52630AFEAEB79B2184E0644D22308B95B94A3A5FB3111B25DCB0265B903584BF

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/3122736c4044e9a22237fffacee80ca1d7604be1 .
Deployed.
