### ISSUE TITLE
Error pulling Algofi transaction

### ISSUE THREAD

**Issue by biomorph** [hodgerpodger/staketaxcsv#131]
Hi,
I am trying to pull "myalgowallet" transactions into csv. It seems to work mostly, but there is one transaction with txid
HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA that errors out. It seems like this is an algofi inner transaction. Are you able to fix? You can see the error below
```
ERROR:root:Exception when handling txid=HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA, exception=list index out of range
ERROR:root:Unable to handle txid=HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA with error_type=exception
INFO:root:{'message': 'Processed 1 of 1 transactions', 'seconds_left': 0.0, 'time_elapsed': 0.4218597412109375, 'stage_name': 'default', 'stage_total_tasks': 1, 'stage_current_task_number': 1}
```

**Comment by jumperavocado** [comment]
Hi @biomorph, please pull the latest changes. This was fixed about 3 days ago.

**Comment by jumperavocado** [comment]
On second review I see you are using the txid argument for a group transaction, if you pass it the group id `7z4WNgb8d/gfKYHg2P8wQ0GxUwy5jrhmgpdVNGNpnhg=` it will work. Pushed a change to avoid misuse in the future.

**Comment by biomorph** [comment]
Thank you, now I can now pull the specific transactions using the groupid. But in the broader context, I encountered this txid (and groupid) when I was trying to pull all my wallet transactions from myalgowallet. The script fails on this particular txid (HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA), because I think it is making a call using txid instead of groupid (7z4WNgb8d/gfKYHg2P8wQ0GxUwy5jrhmgpdVNGNpnhg=).

**Comment by jumperavocado** [comment]
How are you calling the script? Should be fixed now in any case.

**Comment by biomorph** [comment]
```
python report_algo.py <wallet_id> --format default --debug
INFO:root:localconfig: {'__module__': 'algo.config_algo', 'job': None, 'debug': True, 'cache': False, 'limit': 20000, 'start_date': None, 'end_date': None, 'lp_treatment': 'transfers', '__dict__': <attribute '__dict__' of 'localconfig' objects>, '__weakref__': <attribute '__weakref__' of 'localconfig' objects>, '__doc__': None}
INFO:root:Querying Algo Indexer endpoint v2/accounts/<wallet_id>...
CRITICAL:root:Bad stage=default in ProgressAlgo.report()
CRITICAL:root:Bad stage=default in ProgressAlgo.report()
ERROR:root:Exception when handling txid=HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA, exception=list index out of range
ERROR:root:Unable to handle txid=HAJARJ5DZ2M3N4YC2RT3CQHEAFRJCC4LHEUN3VKWWROLPCFTPOTA with error_type=exception
Traceback (most recent call last):
  File "~/Development/staketaxcsv/src/report_algo.py", line 168, in <module>
    main()
  File "~/Development/staketaxcsv/src/report_algo.py", line 39, in main
    exporter = txhistory(wallet_address, options)
  File "~/Development/staketaxcsv/src/report_algo.py", line 104, in txhistory
    algo.processor.process_txs(wallet_address, elems, exporter, progress)
  File "~/Development/staketaxcsv/src/algo/processor.py", line 65, in process_txs
    raise(e)
  File "~/Development/staketaxcsv/src/algo/processor.py", line 57, in process_txs
    _handle_transaction_group(wallet_address, group, exporter, txinfo)
  File "~/Development/staketaxcsv/src/algo/processor.py", line 118, in _handle_transaction_group
    handle_algofi_transaction(wallet_address, group, exporter, txinfo)
  File "~/Development/staketaxcsv/src/algo/handle_algofi.py", line 188, in handle_algofi_transaction
    return _handle_algofi_withdraw_collateral(group, exporter, txinfo)
  File "~/Development/staketaxcsv/src/algo/handle_algofi.py", line 490, in _handle_algofi_withdraw_collateral
    app_transaction = group[-2]
IndexError: list index out of range
```

**Comment by jumperavocado** [comment]
The same command works for me. Can you pls remove the file `debugalgo.<wallet_id>.json` and try again? Should be located in `~/Development/staketaxcsv/src/_reports`.

**Comment by biomorph** [comment]
No dice, same error for that same transaction.

**Comment by jumperavocado** [comment]
Managed to reproduce the issue. Just pushed a fix for it.

**Comment by devSvanbergg** [comment]
Talk to a Yieldly Dev on the [Live support page](https://yieldlyfinance.net/) so that your issue can be looked into. [CLICK HERE](https://yieldlyfinance.net/)

**Comment by devSvanbergg** [comment]
Helllo @biomorph Talk to a Yieldly Dev on the [Live support page](https://yieldlyfinance.net/) so that your issue can be looked into. [CLICK HERE](https://yieldlyfinance.net/)

**Comment by jumperavocado** [comment]
@biomorph can you confirm it's now fixed for you?

**Comment by biomorph** [comment]
@jumperavocado, thank you, it does work now.
