### ISSUE TITLE
Solana token or staking account closure shows fee, not updating balance

### ISSUE THREAD

**Issue by jmatzan** [hodgerpodger/staketaxcsv#134]
When closing a Solana token account or staking account, stake.tax categorizes this transaction as SPEND, the comment field says "fee for _CLOSE_ACCOUNT", and a debit of -0.00005 SOL is recorded.

When there is a balance in this account (as there often is in staking accounts), there are two problems with the results of this transformation:

1. The deposit for whatever was in the account is not shown in the stake.tax output at all.
2. This type of transaction removes the fee from the balance prior to transfer; it does not debit the main account's balance. This is a little unusual in the Solana world, but it's how it is when closing accounts.

Example transaction: https://solscan.io/tx/3onv4QuFKjBpB723XVmxhQD3TnocvnEqUd1RcJ8BqXEP4NfFWqDbEoJkP5eTPY9KnVe27naNyCyo4QbrLLiScYDC

Example CSV (row 7): https://stake.tax/?jobId=2c2a6e5969c749eabb276c3eb34313e4

**Comment by DevPeter46** [comment]
Talk to a Solana Dev on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by hodgerpodger** [comment]
Closing due to older nature of issue.  Reopen if still an issue.
