### ISSUE TITLE
Osmo delegations being categorized as lp rewards

### ISSUE THREAD

**Issue by akrueger** [hodgerpodger/staketaxcsv#135]

**Comment by hodgerpodger** [comment]
probably needs more description to be acted up.  Can DM or email specific transaction also.

**Comment by akrueger** [comment]
Sure, no problem:

https://www.mintscan.io/osmosis/txs/C365BACB328AF4C04E862D2753EE00FD91A7BD30DD730A66200FE7AA266479EE

The csv is outputing both of these as "lp_reward" and rightly marking that as "staking" or "interest". 

In this case, the 18 OSMO is the LP delegation, and the 1.8 OSMO is the LP reward.

**Comment by hodgerpodger** [comment]
Hm, where are you seeing the "lp_reward"?  

My inclination is to say for this transaction, I see:
  * one csv row with 1.5 OSMO claimed rewards (from staking)

I'm guessing lp_reward rows you see is from actually separate LP rewards?  I'll double check the large csv job for this address when this finishes.  Let me know if you see a txid for the lp_reward row--that would help me debug or clarify the issue.

**Comment by akrueger** [comment]
It's producing 2 rows. It's miscategorizing the delegation as an lp_reward. The actual transaction is on the reward while the delegation has the wallet address concatenating the date and asset.

|                |         |           |      |  |  |  |  |           |                                                                    |                                                                                                  |                    |                                             | 
|----------------|---------|-----------|------|--|--|--|--|-----------|--------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|--------------------|---------------------------------------------| 
| 10/26/21 17:43 | STAKING | 1.518334  | OSMO |  |  |  |  |           | C365BACB328AF4C04E862D2753EE00FD91A7BD30DD730A66200FE7AA266479EE-0 | https://mintscan.io/osmosis/txs/C365BACB328AF4C04E862D2753EE00FD91A7BD30DD730A66200FE7AA266479EE | osmosis_blockchain | osmo1jlp2jwj74ltvchlfj4mffkp2fg6mru4k62wr25 | 
| 10/26/21 17:00 | STAKING | 18.831292 | OSMO |  |  |  |  | lp_reward | osmo1jlp2jwj74ltvchlfj4mffkp2fg6mru4k62wr25.2021-10-26.OSMO        |                                                                                                  | osmosis_blockchain | osmo1jlp2jwj74ltvchlfj4mffkp2fg6mru4k62wr25 |

**Comment by hodgerpodger** [comment]
Oi okay, thanks for the details.  Verified the error.

Looks like it's not an issue with the staketax parser but the source data--I'll notify the data provider team.

**Comment by hodgerpodger** [comment]
Okay, the data provider team got back to me.  He astutely pointed out to me that in this address, it's consistent: 

10/26/21 17:00:00: user received 18.831 OSMO rewards from LP pool
10/26/21 17:43:33: user delegates 18.831 OSMO (and claims 1.518334 staking rewards)

So user just happens to exactly delegate (LP autocompound) the LP rewards he/she received 0-2 hours prior.

**Comment by akrueger** [comment]
There is no LP reward listed on the block explorer that I can find at 17:00. 18 OSMO is a massive LP reward--far greater than the amounts LP-ing in this wallet. Could it be a staking reward?

https://www.mintscan.io/osmosis/txs/C365BACB328AF4C04E862D2753EE00FD91A7BD30DD730A66200FE7AA266479EE

The delegation of the 18 OSMO auto-claims a smaller amount of 1.5 OSMO which is then immediately delegated itself, but I see nothing on the explorer showing this 18 OSMO ever doing anything but being delegated in this time period.

<img width="1211" alt="Screen Shot 2022-03-29 at 17 38 17" src="https://user-images.githubusercontent.com/1644520/160718610-421cbf82-f764-48a4-8bd9-375318a4ac4d.png">

**Comment by akrueger** [comment]
I got this message from the Osmosis Discord channel:

> _LP rewards are minted via an on-chain module directly to your wallet. Because this is a module transaction the block explorers currently utilized in the ecosystem cannot read the block event associated with these rewards. A native solution is being developed to help you track your LP rewards, but in the meantime manual tracking remains your best option._

So it seems it's not available on-chain, at least directly from the wallet. It's operating off its own module. Woof.

**Comment by hodgerpodger** [comment]
Yup
