### ISSUE TITLE
[algorand] Any plans to support AlgoFi and the new vault functionality for governance?

### ISSUE THREAD

**Issue by pbennett** [hodgerpodger/staketaxcsv#145]

**Comment by jumperavocado** [comment]
Hi Patrick, the new vault functionality should already be supported, as it's equivalent to the existing deposit/withdraw collateral functions. I'll be adding support for the governance rewards paid into the vault soon after I add support for Folks transactions.

**Comment by jumperavocado** [comment]
Hi @hodgerpodger, we can close this one.
