### ISSUE TITLE
[algorand] DEGEN token imports into Koinly as DEGEN, an ERC20 token (Degen Finance)

### ISSUE THREAD

**Issue by pbennett** [hodgerpodger/staketaxcsv#146]
You can edit the transaction and Koinly has a 'Degen token (algo)' you can switch it to, but it won't stick because as soon as you import an updated CSV it will add a new transaction to the old (incorrect) DEGEN.
I'm not sure if Koinly has a way of fixing this at the moment as I don't think they let you specify the other token names in the unit name.

**Comment by jumperavocado** [comment]
I can remap this ASA's name to its Koinly id: [https://app.koinly.io/p/markets/124845](https://app.koinly.io/p/markets/124845). As simple as switching "DEGEN" for "ID:124845".
