### ISSUE TITLE
Osmo/UST Liquidity Pair and Outgoing IBC transfers for Stars and SCRT

### ISSUE THREAD

**Issue by ltsand3** [hodgerpodger/staketaxcsv#149]
First off thanks for taking the time to make such a useful piece of software! 

Everything works flawlessly except for a few issues. 
-Swapping from null tokens back to their base pairs seems to not be working, at least for the Osmo/UST pair
-IBC transfer from OSmosis and secret appear not to be working

Regardless if you get to this message or not, stake. tax has made my life, and countless others' lives much easier. Kudos to you for putting your skills to work to help the less technically savvy. 

Thanks again!

**Comment by cccassidy** [comment]
Ran into the same issue with OSMO/UST pair, after looking at the block explorer on Mintscan I don't see anything there either.  I ended up creating 2 transactions by hand 1/2 of the pool tokens -> UST, 1/2 pool tokens to OSMO.

**Comment by hodgerpodger** [comment]
closing due to old issue that I'm unable to track down easily.  reopen if desired.
