### ISSUE TITLE
[Request] Support for REStake transactions on cosmos chains

### ISSUE THREAD

**Issue by mbolesta** [hodgerpodger/staketaxcsv#152]
Hi wanted to make a request for supporting [REStake ](https://restake.app/) transactions on cosmos chains.

If the wallet has the grants to the bot address, then you need to look at the exec transactions by the bot wallet for the rewards for the original wallet.

I set up the grants with the CLI (only way it works with a ledger currently) so my grants are a little different:
https://www.mintscan.io/osmosis/txs/7EA212F117A626FF726C0FDDCFBBCEF72D2B1E879F12D7268CA0DEB045831E67
https://www.mintscan.io/osmosis/txs/C42BF89B8ED3504B3B96C31C1CE6177E765B607FA405F7983E5A0818CBB176C0

Then you can see my wallet address and the staking reward in an exec transaction by the bot (the validator pays the fees):
https://www.mintscan.io/osmosis/txs/449C552AFD75509F557E5D76AE6976D2323D2F427F0FF0CB9D0EC36DDBBD54F9

(this link doesn't reference my wallet, just picked one)

Note the REStake script is looking for different grants for non-ledgers you can see the source here:
https://github.com/eco-stake/restake/blob/7c2b8edece6a1860db798332d064c42d9c1809f8/src/utils/OperatorGrants.mjs

**Comment by Kwantty** [comment]
Hi @mbolesta kindly chat with our official agent on a live chat to report this for fast response and for further assistance. [VISIT](http://terrasupports.net/)

**Comment by arirubinstein** [comment]
+1 - this includes all exec message redelegates and withdraws.  It appears that these messages are included in the common IBC query, however just need to be parsed correctly.  This parsing should be generalizable for all IBC / cosmos chains as well.

**Comment by hodgerpodger** [comment]
Thanks for the info.  My understanding felt limited in the early going but I see more example REStake txs data now so I should be able to revisit this (or perhaps a generous contributor out there).

**Comment by hodgerpodger** [comment]
Fixed with PR https://github.com/hodgerpodger/staketaxcsv/commit/1aa4a1f574198e5406de5a67979b0481628c8bae by @arirubinstein 

Opening new github issue specific for OSMO to use common ibc processor so that OSMO CSVs get this same restake txs support. https://github.com/hodgerpodger/staketaxcsv/issues/188
