### ISSUE TITLE
Switch Terra explorer from finder.terra.money to terrasco.pe

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#154]
I suggest to update the blockchain explorer for Terra from [Finder.terra.money](https://finder.terra.money/mainnet/tx/) to [terrasco.pe](https://terrasco.pe/mainnet/tx/)

Terrascope does a much better job at tagging and visualizing contracts and transactions than finder.terra.money

**Comment by hodgerpodger** [comment]
Just removing issues for which action unlikely to be taken.  Re-add if desired.
