### ISSUE TITLE
Double accounting of fee for sending SOL

### ISSUE THREAD

**Issue by OnTheHedge** [hodgerpodger/staketaxcsv#156]
The following issue affects Koinly output format when sending SOL. The fee for sending SOL appears both in the Fee Amount column (where it belongs) and is also (incorrectly) included in the Sent Amount column. For example, in the following transaction, 0.1 SOL is sent from the address oyst...5Wj4 to 3b3X...mmCp with a fee of 0.000005 SOL. The "Sent Amount" is incorrectly showing on stake.tax as 0.100005 SOL (it should be 0.1 SOL). The TX hash is 3YPjvVhijKh2WuhJYgDyqs5SdYZwMEeAYCejLRhs98S4viicz2rBzMpvGbr9pfLRKwCKM2GNZYkNWxFYLWg21CL6

**Comment by hodgerpodger** [comment]
Thanks for report.  Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/535e811e881adf986b6dc8a5c1656c07beaa3bd9

**Comment by OnTheHedge** [comment]
Thanks for making stake.tax :)
