### ISSUE TITLE
"Unable to determine lp currency"

### ISSUE THREAD

**Issue by Joshdw** [hodgerpodger/staketaxcsv#158]
Hey! I'm having issues using this tool with Terra chain, I am getting "Unable to determine lp currency for addr". Any ideas what the reason could be?

```
INFO:root:localconfig: {'__module__': 'terra.config_terra', 'minor_rewards': False, 'lp_treatment': 'transfers', 'ibc_addresses': {}, 'currency_addresses': {}, 'decimals': {}, 'lp_currency_addresses': {}, '__doc__': None, 'job': None, 'debug': True, 'cache': False, 'limit': 20000, 'koinlynullmap': None}
INFO:root:max_txs: 20000, max_queries: 200
CRITICAL:root:Bad stage=default in ProgressTerra.report()
INFO:root:Querying FCD url=https://fcd.terra.dev/v1/txs?account=XXX&limit=100..
INFO:root:Wrote to _reports/debug.gettxs-XXX-0.json for debugging
INFO:root:{'message': 'Retrieved total 78 txids...'}
CRITICAL:root:Bad stage=default in ProgressTerra.report()
INFO:root:Querying lcd for contract = XXX ...
INFO:root:Requesting url https://lcd.terra.dev/wasm/contracts/XXX?
INFO:root:init_msg: {'name': 'Kuji', 'symbol': 'KUJI', 'decimals': 6, 'initial_balances': [{'address': 'XXX', 'amount': '150000000000000'}]}
INFO:root:Found symbol=KUJI decimals=6
INFO:root:Querying lcd for contract = XXX ...
INFO:root:Requesting url https://lcd.terra.dev/wasm/contracts/XXX?
INFO:root:init_msg: {'name': 'Kuji', 'symbol': 'KUJI', 'decimals': 6, 'initial_balances': [{'address': 'XXX', 'amount': '150000000000000'}]}, txid:XXXX
ERROR:root:Exception when handling txid=XXX, exception=Unable to determine lp currency for addr=XXX, txid=XXXX
ERROR:root:Unable to handle txid=XXXX with error_type=exception Traceback (most recent call last):
  File "report_terra.py", line 177, in <module>
    main()
  File "report_terra.py", line 42, in main
    exporter = txhistory(wallet_address, options)
  File "report_terra.py", line 125, in txhistory
    terra.processor.process_txs(wallet_address, elems, exporter, progress)
  File "terra\processor.py", line 29, in process_txs
    process_tx(wallet_address, elem, exporter)
  File "terra\processor.py", line 80, in process_tx
    raise (e)
  File "terra\processor.py", line 67, in process_tx
    terra.col4.handle.handle(exporter, elem, txinfo)
  File "terra\col4\handle.py", line 184, in handle
    return handle_lp.handle_lp_stake(exporter, elem, txinfo)
  File "terra\col4\handle_lp.py", line 156, in handle_lp_stake
    lp_currency = util_terra._lookup_lp_address(lp_currency_address, txid)
  File "terra\util_terra.py", line 359, in _lookup_lp_address
    raise Exception("Unable to determine lp currency for addr={}, txid={}".format(addr, txid))
Exception: Unable to determine lp currency for addr=XXX, txid=XXXX
```

**Comment by hodgerpodger** [comment]
Pretty unsure.  Seems like it just may be a bug or lack of support for new data structure associated with KUJI.

**Comment by hodgerpodger** [comment]
If you're using --debug flag, try it without the debug flag, since it will stop when --debug flag is used.

**Comment by Joshdw** [comment]
Cheers, that worked great!
Will close this now.

Out of curiosity, is it possible to increase the transaction limit from 100 to 1000? Thanks

**Comment by Joshdw** [comment]
Sorry, have to re-open with another question. It seems like all of KUJI's bonding doesn't seem to be working.

TXID example: 99214AF88EEFA26DA5398E56E6086D4E4356525538D33326985485A288922974

Results in the CSV showing "_UNKNOWN" in the tx_type column, and nothing in received_amount, received_currency, sent_amount and sent_currency.

It does look like it's something related to KUJI's new sKUJI bonding.

Thanks!

**Comment by Joshdw** [comment]
Also, sorry for another question,
using Stake.Tax site transfers of certain tokens appear correctly, running this repository locally, a lot of these transactions show _UNKNOWN.

For example, 5A0D0E811D47EC986454970FBA78EF64B5C13BAAA7E10038B61D2C1F5AA85640

On stake.tax csv output it'll show it correctly as a transfer, showing sent amount and currency. If I run it myself in Python I get "_UNKNOWN".

I think it might be because it doesn't have the currency info saved maybe? Do you know what could be happening?

Sorry again for all the questions, appreciate your time and for sharing this great repo on here!

**Comment by hodgerpodger** [comment]
Not immediately obvious but maybe required environment variable not set.

To test if this is the case, try ```export TERRA_LCD_NODE=https://lcd.terra.dev```
If this is the case, follow https://github.com/hodgerpodger/staketaxcsv#usage

**Comment by Joshdw** [comment]
Thanks, I'm actually using figment.io (https://columbus-5--rpc--full.datahub.figment.io/apikey/) although switching back to https://lcd.terra.dev to test it didn't fix it. I'll do some digging see if I can find any mistakes I've made

**Comment by Joshdw** [comment]
Right, did some digging. I've managed to get KUJI kind of set up.

Basically, I added this to the CONSTANTS.PY

```
CONTRACTS_KUJIRA = [
    "terra1w7gtx76rs7x0e27l7x2e88vcr52tp9d8g4umjz", # governance staking
    "terra1vvj874nwtmxk0u0spj83d364xyhqk2e652jrck", # rewards pool
    "terra1s6tqnxqk0mqj80uhjq9h8d5qc64lagn3ljlwkh", # governance
]
```

And under terra/handle.py, function def handle, I added this:

```
elif util_terra._any_contracts(CONTRACTS_KUJIRA, elem): #CUSTOM KUJIRA
        if execute_type == ex.EXECUTE_TYPE_BOND:
            return handle_lp.handle_lp_deposit(exporter, elem, txinfo)
        elif execute_type == ex.EXECUTE_TYPE_UNBOND:
            return handle_lp.handle_lp_withdraw(exporter, elem, txinfo)
```

This basically treats sKUJI bonding/unbonding as deposits/withdrawals instead of defaulting to the handle_lp_stake, handle_lp_unstake functions.

Still testing things around but that seems to have fixed anything sKuji related. Now I'm digging into an Orion deposit, which I think is the exact same issue as sKUJI, simply have to add https://terrasco.pe/mainnet/contracts/terra135mjmscm37mp5tu5ghp00lp374fsjaqksmjfh8 to the CONSTANTS and treat it as a lp_deposit instead of stake. Will work on that now.

Cheers

**Comment by hodgerpodger** [comment]
Nice!
