### ISSUE TITLE
[ALGO] Classify Buy and Sell transactions from CEX

### ISSUE THREAD

**Issue by Michele971** [hodgerpodger/staketaxcsv#177]
Actually the transactions that come from/to the centralised exchanges are labeled as "transfer".
Maybe, the report could indicate if the transactions are a purchase or not (using Machine Learning or probability).

**Comment by jumperavocado** [comment]
Hi Michele, thanks for the report. The fact that the transaction comes from a CEX is irrelevant. When you import the CSV to your tax software it'll be able to detect whether the source/destination address belongs to you and will label it appropriately.
