### ISSUE TITLE
BTSG airdrop showing up as multiple deposits to wallet, when only one deposit occurred 

### ISSUE THREAD

**Issue by bruxisma** [hodgerpodger/staketaxcsv#18]
Hello, and thank you for writing this tool. It's a lifesaver

I recently did an export of my wallet, and when looking at the exported data, it would appear that [Osmosis BTSG Pool 560] reward incentives or airdrop (https://www.mintscan.io/osmosis/txs/57E82EA67EA00C54EC6068F2860E0DA227532C5F5013745F7071808FD4786471) were reported as deposits into my wallet. The following line is repeated in the exported CSV 41 times.

```
2021-12-31 17:03:02,,,<AMOUNT-HERE>,BTSG,,,,,,,57E82EA67EA00C54EC6068F2860E0DA227532C5F5013745F7071808FD4786471-560
```

The issue is that I only received the amount just once, and this has resulted in nearly every tax tool thinking that I earned the entire USD value of the airdrop. 😧 

I've been able to manually verify and fix the CSV locally, but wanted to bring this to your attention in case someone else runs into it 😅

**Comment by hodgerpodger** [comment]
Oi, thanks for the awesome details and description!  Will investigate asap

**Comment by hodgerpodger** [comment]
Do you mind DM'ing (@staketax or support@stake.tax) me your wallet address or bookmark url? Looks like it's an issue specific to your wallet address for that airdrop.  If not comfortable, no worries.  Just got I'd ask.

**Comment by hodgerpodger** [comment]
oh wait nm, I think I can figure out something.

**Comment by hodgerpodger** [comment]
Just checked: seems like it's currently working for the above implied transaction/address. 

I thought I fixed this issue recently-ish, but my memory is fuzzy exactly when (maybe like a week ago).  So I'm wondering if you created the CSV possibly before the fix?  

If you created this CSV after my fix, do you mind DM'ing wallet address or bookmark url?  I believe it would likely be an address-specific issue in regards to the airdrop transaction.  If not comfortable, no worries.

**Comment by bruxisma** [comment]
Hi, sorry for not responding as quickly. I had filed this bug during my lunch break 😅 

Regarding when the export finished, it was actually 30 minutes before I filed this issue so unless you deployed sometime today I don't think it would have been from that.

That said, I completely forgot to bookmark the data export, and while I would normally be fine with sending stuff like this over I kind of need to think it over and process whether I'm comfortable with sharing that or not. Give me some time to think it over? (also I assume by DM you mean on twitter 😅)

**Comment by hodgerpodger** [comment]
Yup, Twitter DM.

Of course, take your time and cautiousness is well understood.

**Comment by hodgerpodger** [comment]
Alrighty, no need to send anymore.  I found an example and deployed a fix.  Thanks for reporting the issue!

**Comment by bruxisma** [comment]
Thank you! I had actually completely spaced DMing you my info on twitter. Glad it worked out in the end 🙂
