### ISSUE TITLE
Accointing export: missing header

### ISSUE THREAD

**Issue by danielkleinert** [hodgerpodger/staketaxcsv#189]
When trying the Accointing export I get the following error:

```
We found some errors in the following rows:
Row 1 | Invalid headers | Your file seems to be missing headers: "comments (optional)"
```

**Comment by hodgerpodger** [comment]
Thanks for report!

Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/6dce5133f5d2285faa3b5230b7dd547a3448acf3 and deployed to website
