### ISSUE TITLE
Support for Kujira

### ISSUE THREAD

**Issue by SxMShaDoW** [hodgerpodger/staketaxcsv#192]
Would be great to support Kujira based CLOB transactions

**Comment by SxMShaDoW** [comment]
broke a few things but got a report generated: https://github.com/hodgerpodger/staketaxcsv/compare/main...SxMShaDoW:staketaxcsv:kujira

Would probably need someone with more knowledge of Kujira / cosmo / staketax to better handle this as it seems a bit more complex since its a CLOB and smart contracts that handle the trading of assets vs a true swap functionality. 

Also need to either support multiple explorers in the processor (either common or in kujira) or ask mintscanio to support Kujira.

**Comment by hodgerpodger** [comment]
Began KUJI CSVs.
