### ISSUE TITLE
Juno not returning transactions prior to July 30th

### ISSUE THREAD

**Issue by bigshooTer39** [hodgerpodger/staketaxcsv#193]
I saw some changes were made to the Juno transactions download.  It now shows the received amount which is fantastic!  Thank you very much, that has saved me a ton of time.

There is an issue I'm seeing where transactions prior to July 30th are no longer being returned.  There is a note saying transactions prior to April 12th are unavailable on Juno chain, but I am seeing everything prior to July 30th missing.

I am actually seeing the same thing with Evmos as well.  After you initially added support for Evmos, I was able to export all transactions for this year which went back to May.  However as of 2-3 weeks ago, I can no longer return the earlier transactions.  It also only goes back to July for Evmos.

Let me know if you need anything from me and happy to provide.

**Comment by mbolesta** [comment]
I'm seeing this too. Approximately 180 transactions with the earliest being	2022-07-29 18:29:30.

**Comment by bigshooTer39** [comment]
I contacted Robert at atomscan.com who explained the issue to me and has gone above and beyond trying to help.

Juno forked at the end of July. As of right now, it’s impossible to view your Authz/restake auto compoundtransactions for Juno prior to July 30th.

Robert is trying to find someone who has a copy of the the transactions. Once he does, he said that he was going to spin up a node. I’m not sure if that means they will be available on atomscan or if they will be available somewhere else. I haven’t heard from him in a week or two, hopefully that’s not bad news.

Thanks
bigshooter

**Comment by mbolesta** [comment]
@bigshooTer39 thanks for the update. I started using REStake in mid April so I'd love to get those if possible.

Before that I was manually compounding, but I don't see any of those transactions, everything cuts off with the fork at the end of July. I started staking JUNO in the beginning of March. But I do see the disclaimer about no data before 4/12/2022 so maybe that's the issue there.

**Comment by bigshooTer39** [comment]
No problem. I’ve reached out to everyone I could think of. Robert at AtomScan has been quite helpful. In return, I’ve started using atomscan over mintscan as much as possible. Mintscan doesnt show restake autocompound, but atomscan, Big Dipper, ping.pub, and some others do. I’m incredible thankful for the work that has been put into stake.tax. It just absolutely baffles me that an ecosystem the size of cosmos doesn’t have an explorer with export functionality. I followed up with Robert from atomscan yesterday but haven’t heard back yet. I don’t want to hound him bc he would be doing me/us/the community a favor.

What we need is to find someone with a backup of Juno blockchain so he can stand up a node. If he can get the data, he’ll spin something up.

About 2-3 weeks ago, I asked the guythat runs stake.tax (likely copied on this) to add the memo field to the csv exports and it looks like he did. It saved me a ton of time. I download my transactions and upload them to a portfolio tracking service I use and a database that I built.

For the service, I use CoinStats to track my holdings. I like that it harmonizes all your transactions into 1 format that you can download. They have a lot of APIs and support the most networks. I’ve tried koinly, delta, and CoinTracker as well but CoinStats wins. If you’re interested, my referral is below. Using it gives you a couple hundred sparks which is there internal token. I think you get 3 month subscription to their Pro tier as well. You can use sparks to buy their NfTs, redeem them for things like a Bitcoin clock, or once you have enough can buy a lifetime subscription with them. Holding 2 of their nfts gets you lifetime premium as well.

Honesty the free tier is much more substantial that anyone else’s. If you’re a light trader it should probably be fine. I outgrew it quickly though. Enjoy!

https://invite.coinstats.app/r?i=mXtuCb1640718913599

Shooter

**Comment by mbolesta** [comment]
@hodgerpodger saw you switched Juno over to RPC and I am seeing some history now. But it seems to have lost the ReStake msexec transactions in the process?

Not sure if you're aware...  thanks for making updates!

**Comment by hodgerpodger** [comment]
Thanks!  Didn't know.  Created new issue this particular bug doesn't get lost: https://github.com/hodgerpodger/staketaxcsv/issues/240

I think I will close this issue due to juno rpc fixes.  Please reopen if still seeing related issues.
