### ISSUE TITLE
Luna1 https://lcd.terra.dev/cosmos/tx/v1beta1/txs returns 403

### ISSUE THREAD

**Issue by r3tero** [hodgerpodger/staketaxcsv#196]
Luna1 report is not working.

https://lcd.terra.dev/cosmos/tx/v1beta1/txs returns 403, permission denied.

**Comment by hodgerpodger** [comment]
Thanks for the info.  I'll need to update documentation somewhere but looks like lcd.terra.dev became restricted sometime around the birth of Terra 2.0.  You can find alternative LCD endpoints here https://github.com/cosmos/chain-registry/blob/master/terra/chain.json .

Example:
```
export STAKETAX_TERRA_LCD_NODE=https://...
```

**Comment by hodgerpodger** [comment]
Updated code not to use lcd.terra.dev as default: https://github.com/hodgerpodger/staketaxcsv/commit/e35cae782467b28836b2fa85e88686a73fd80ad3
