### ISSUE TITLE
Lp rewards from osmosis chain not showing after 10/09

### ISSUE THREAD

**Issue by OliverFishCode** [hodgerpodger/staketaxcsv#205]
Lp rewards are showing correctly in stake.tax or api call through the 9th. However, after the 9th there is no record of lp rewards. Anyone know why or having the same issue?

Api call used in browser to see osmo lp rewards: https://api-osmosis-chain.imperator.co/lp/v1/rewards/historical/{wallet_public_address}/osmo

**Comment by hodgerpodger** [comment]
Closing.  Reopen if still seeing this issue.
