### ISSUE TITLE
[SOL] Support Jupiter Aggregator V3 and V4

### ISSUE THREAD

**Issue by ishiDACo** [hodgerpodger/staketaxcsv#208]
Jupiter Aggregator V2 was supported in #161.
It has since been updated to Jupiter Aggregator V3 and V4, so V3 and V4 support is required.

**Comment by hodgerpodger** [comment]
Merged fix and deployed to stake.tax.  https://github.com/hodgerpodger/staketaxcsv/pull/209

Thanks!
