### ISSUE TITLE
TERRA: Miscalculation on Anchor Borrow transactions

### ISSUE THREAD

**Issue by rymalia** [hodgerpodger/staketaxcsv#22]
I just imported a new TERRA staketax file into Koinly and noticed that all BORROW transactions are misstating the gross total impact. There's sort of 4 components to a BORROW transaction with Anchor:

1. The usual Terra transaction fee -- the small fee charged to all transactions on the blockchain.
2. Borrow Amount: the total amount being borrowed and needs to be repaid.
3. Receive Amount: this is the amount deposited into the users wallet.
4. Anchor Borrow Fee: I'm not sure on the correct title or definition for this fee, but this fee is displayed to the user when they choose their borrow amount in Anchor Protocol, and is taken out of Borrow amount to result in the Receive Amount.

Right now it appears that staketax is disregarding  (4), the Anchor Borrow Fee, resulting in no visibility to those costs. 

To resolve, the Anchor Borrow Fee could be combined with the existing transaction fee amount.

Screenshots below of an Anchor Borrow transaction, highlighting the fee that's not being accounted -- it shows up in a a few locations: 
<img width="616" alt="A Screen Shot 2022-01-10 at 9 29 30 PM" src="https://user-images.githubusercontent.com/705882/148887511-a2b9794d-6203-4bca-bd8a-f45b51259f39.png">
<img width="626" alt="B Screen Shot 2022-01-10 at 9 30 06 PM" src="https://user-images.githubusercontent.com/705882/148887516-dc2010b4-aa76-4f58-9924-3ba98e7a9e74.png">
<img width="702" alt="C Screen Shot 2022-01-10 at 9 30 27 PM" src="https://user-images.githubusercontent.com/705882/148887518-45020cb6-d47b-4e0d-8591-0a931c7c8cdc.png">
<img width="496" alt="D Screen Shot 2022-01-10 at 9 30 57 PM" src="https://user-images.githubusercontent.com/705882/148887520-31ccf10e-4175-4542-8ffe-36f81a609083.png">

**Comment by hodgerpodger** [comment]
Thanks for reporting!  

Just to confirm: it should be $0.17 fee on borrow 100 UST, if I'm reading this from my phone correctly?

Should be able to fix very soon.

**Comment by rymalia** [comment]
Yep, that 0.169337 UST to be exact. 👍

**Comment by hodgerpodger** [comment]
Alrighty fixed and deployed.  

Fixed new version:
csv fee = "transaction fee" + "contract fee"
borrow amount = actual borrowed amount

Previous version
csv fee = "transaction fee"
borrow amount = actual borrowed amount - "contract fee"

**Comment by hodgerpodger** [comment]
Just noting: https://github.com/hodgerpodger/staketaxcsv/commit/b0ee5c89e414e6ac916ae1172b99d7e3342b870a

**Comment by coultenholt** [comment]
This breaks me actually, and I have transactions reporting negative balances. I think someone should reevaluate this, because the fees arent adding up and sending me negative.

**Comment by rymalia** [comment]
Can you find any similar transactions in col4 timeframe and current col5 timeframe, to compare against?
