### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by fridolinvii** [hodgerpodger/staketaxcsv#222]
Thanks for creating the program. I tried to run it online but I had some issues.

After installing python3.9 and all the packages, I run

`python3.9 staketaxcsv/report_atom.py "cosmosMYADRESS" --limit 5`

And I get the following error:

> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

After some investigating I found that the issue is in 

> staketaxcsv/atom/api_lcd.py

at the function 

>  def _query(uri_path, query_params, sleep_seconds=1):

It seems when collecting the information over the API with

> response = requests.get(url, query_params)

I got the following:

> INFO:root:Requesting url https://api.cosmos.network/cosmos/tx/v1beta1/txs?order_by=ORDER_BY_DESC&pagination.limit=50&pagination.offset=0&pagination.count_total=True&events=message.sender%3D%27{cosmosMYADRESS}%27

And when adding 

`https://api.cosmos.network/cosmos/tx/v1beta1/txs?order_by=ORDER_BY_DESC&pagination.limit=50&pagination.offset=0&pagination.count_total=True&events=message.sender%3D%27{cosmosMYADRESS}%27`

manually on the website [https://v1.cosmos.network/rpc/v0.41.4](https://v1.cosmos.network/rpc/v0.41.4) I get no response there aswell. Am I missing something?

**Comment by hodgerpodger** [comment]
Thanks for trying it out!  Looks like the default node api.cosmo.network is not operational.  I'll have to update it with a sensible default and probably a better error message if the node is unreachable.

In the meantime, you can try:
```
export STAKETAX_ATOM_NODE=https://node.atomscan.com
```

Let me know if you have continued issues here.

**Comment by fridolinvii** [comment]
Yes, it worked. Thank you very much for your quick reply!
