### ISSUE TITLE
add to algorand standard asset list 

### ISSUE THREAD

**Issue by hodgerpodger** [hodgerpodger/staketaxcsv#225]
Got an email to staketax support and relisting here (with permission) because I'm not familiar with how to immediately address:

```
I downloaded my Algorand wallet transaction history and noticed a few of the Algorand Standard Assets 
are not being imported properly and mislabeled as other assets with the same/similar name. I've included 
them below with the corresponding correct Algorand asset ID. Can you add these to the Algorand Standard 
Asset list?

FMT (Fairmeme token): 361940410
Socks (sockhodler): 452047208
Rev: 772212313
Ghost: 714773890
```

@jumperavocado if you're around and eventually available, guessing this is right up your alley

**Comment by jumperavocado** [comment]
Sure, just need to add a Koinly mapping for these tokens.

**Comment by hodgerpodger** [comment]
Ooh okay.  Didn't catch that. In that case got it. Thanks!

**Comment by jumperavocado** [comment]
Just had a look and can't find them in Koinly. There are hundreds of these meme tokens. Unless this user sends us the exact Koinly ID we won't be able to add a mapping. Workaround is for him to manually remove transactions for these tokens from the CSV (there won't be pricing in Koinly anyway).

**Comment by jumperavocado** [comment]
Closing this. We need users to provide Koinly IDs to add assets.
