### ISSUE TITLE
TERRA: bLUNA swaps missing - their "_BOND" transaction type should be handled like a trade

### ISSUE THREAD

**Issue by rymalia** [hodgerpodger/staketaxcsv#23]
Just noticed in my Koinly file that none of the swaps of LUNA being swapped for bLUNA are included. In the raw data on the staketax csv results page, these transactions show as  [TX_TYPE: _BOND]. I think these should be handled like a regular swap or trade:  swapping x LUNA for y bLUNA.

<img width="595" alt="Screen Shot 2022-01-11 at 12 16 56 AM" src="https://user-images.githubusercontent.com/705882/148906719-6b6e4458-1ce6-4cb6-a19d-419de08240d4.png">

**Comment by hodgerpodger** [comment]
yup, sounds good.  will do.

Note: early on, it was difficult to predict how users would want this to be handled by end tax websites.  I think forcing user to deal/edit with bLUNA in tax websites is better than manual entry.

**Comment by hodgerpodger** [comment]
fixed and deployed
