### ISSUE TITLE
LUNA vs LUNC Price history on Accointing

### ISSUE THREAD

**Issue by danbryan** [hodgerpodger/staketaxcsv#236]
Hey there,

I downloaded a CSV from stake.tax and removed all rows after 4/26/2022.  (Pre Luna Crash).  I did this because the tool im comparing to has not finished indexing osmosis.

I think either I, or stake.tax is miscalculating some values for LUNA Classic.  I think whats happening is accointing tries to look up the price of LUNA (Terra2) on February 5th, when instead it should be looking up the price of LUNC (Terra1) on Feb 5th.  it confusing, because Classic uses to be called LUNA, but i think accointing changed this.  Would love your thoughts on this if you think I am wrong.

For example, Pool 561

![image](https://user-images.githubusercontent.com/807940/213882153-0d22695c-a892-4fc8-99bd-6bd4a432aae0.png)

Both identify that there is 3205.64 GAMM-561s 

If you compare the CSVs, stake.tax uses LUNA

Staketax:
![image](https://user-images.githubusercontent.com/807940/213882225-d126658a-7bbd-4220-8a6c-4d5d7980f9fc.png)

But, i think the correct token, at least for accointing, should be LUNC
![image](https://user-images.githubusercontent.com/807940/213882279-db261de0-d116-401f-9bf2-f3989b68efba.png)

**Comment by hodgerpodger** [comment]
Closing older issues with no action.  Wasn't sure how to resolve.
