### ISSUE TITLE
Algo - Defly Wallet Limit Orders

### ISSUE THREAD

**Issue by dukecc82** [hodgerpodger/staketaxcsv#239]
I've noticed that I'm not getting any details much when using the limit orders feature in defly wallet.  I believe these are going through a smart contract.   The normal market orders seem to be fine.   The transactions that are being picked up show _unknown.   Because of this it's not showing any transactions in koinly.   I am hoping by opening this someone can shed some light on the issue and maybe produce a fix/roadmap to include these smart contracts.

**Comment by jumperavocado** [comment]
At the moment Defly/Deflex transactions are not supported in stake.tax, that being said there was a fix a couple of days ago that will make transfers visible even if the specific dapp is not supported (thought not properly tagged or grouped) and should be deployed soon.

No timeline for when this will be fully supported as it's an open-source contribution and depends on when I get some free time to code it.

**Comment by dukecc82** [comment]
Ok thanks for your response and time.

**Comment by jumperavocado** [comment]
Deflex limit orders are now supported. They'll be available in the website in the next release.

**Comment by dukecc82** [comment]
Awesome thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
