### ISSUE TITLE
CSV support: tax.crypto.com

### ISSUE THREAD

**Issue by arno01** [hodgerpodger/staketaxcsv#24]
That'd be cool to see https://tax.crypto.com support!

**Comment by deten** [comment]
Considering tax.crypto.com is the only really free option out there, support would be tremendous.

**Comment by hodgerpodger** [comment]
Okay, I'll try and add it tomorrow.

**Comment by hodgerpodger** [comment]
Deployed tax.crypto.com CSVs to stake.tax.

I believe there's some inherent issues with tax.crypto.com like limited currencies and incorrect restrictions but added best support given limitations.
