### ISSUE TITLE
JUNO:  ReStake msexec transactions broke after rewrite to use rpc data processing (reported by user)

### ISSUE THREAD

**Issue by hodgerpodger** [hodgerpodger/staketaxcsv#240]

**Comment by mbolesta** [comment]
Seems like the switch to RPC broke ReStake msexec transactions for STARS too...I assume it's just generally not supported at the moment.

**Comment by hodgerpodger** [comment]
If any folks can give sample transactions (DM twitter staketax, DM discord, email support@stake.tax, etc.) for ReSTake on JUNO or STARS that would be most helpful to resolve this issue.  I've only seen one sample transaction but it's tough to conclude an implementation definitively (I notice that mintscan does not provide accurate details for this sample transaction).

**Comment by mbolesta** [comment]
@hodgerpodger you just want a REStake transaction? https://www.mintscan.io/juno/txs/526DE20D6074869AA6B9048F6AC6BD964FCEF519A16C3E07754512A48AD09478
https://www.mintscan.io/stargaze/txs/3402F9631CB82B0B7D2608504EEFBCBD97722684304F26D67C78955C20B72996

**Comment by hodgerpodger** [comment]
yup @mbolesta thanks!

**Comment by hodgerpodger** [comment]
curious @mbolesta (or anybody else) if you have time: looking at https://www.mintscan.io/juno/txs/526DE20D6074869AA6B9048F6AC6BD964FCEF519A16C3E07754512A48AD09478 as an example, would the expected results be (don't care about exact numbers):

1st: .020166 delegated, .000194 reward
2nd: .0203346 delegated, .000689 reward
...

This is my educated guess but I'd like to get some verification from a restake user or anybody familiar with it (since the raw rpc data is not labeled very distinctly).

**Comment by mbolesta** [comment]
@hodgerpodger looking at that transaction the amount is what is being "restaked", the auto claim reward is what you are claiming as a staking reward.

So in the 1st message 0.020166 is being restaked and 0.020360 has been claimed as a staking reward.

![Screenshot 2023-02-15 at 10 11 52 PM](https://user-images.githubusercontent.com/1823276/219258819-fc708c57-ca1b-428e-953d-9b9b0f716177.png)

I'm not sure where you got the .000194 reward?  I confirmed with the old LCD code the auto claim amount was what was showing as the staking reward.

**Comment by hodgerpodger** [comment]
Ooh okay.  Thanks.  I got stuck in my own way of thinking there for a good while.

**Comment by mbolesta** [comment]
I'm not 100% sure but that difference may be used for fees, paid by the validator's bot? I don't think it's the validator's commission, in this case 5% ...

**Comment by hodgerpodger** [comment]
Fixed with [stars13jvl2q0rxyqwjlucrlhrc8pd9zvlgc5hnlg3wh](https://github.com/hodgerpodger/staketaxcsv/commit/2a27937e479f6c0775c71177338017b2f1f4989d)

**Comment by mbolesta** [comment]
@hodgerpodger hey thanks for fixing this can finally do my JUNO taxes!
