### ISSUE TITLE
Algofi v2 lend-and-earn stake/unstake incorrectly calculating earnings due to basset price handling

### ISSUE THREAD

**Issue by tonyhong8** [hodgerpodger/staketaxcsv#245]
It looks like bAssets are currently directly mapped to be the equivalent standard asset (eg., in function **get_transfer_asset**). But because basset prices are actually dynamic relative to the standard assets, this leads the  function **_handle_algofiv2_lend_unstake** to calculate earnings incorrectly.  An example:

I had a 500 USDC staking transaction that exchanged USDC with b-USDC at a rate of 
1.002088 b-USDC for each USDC 

to yield 498.9582 b-USDC

5 days later, I decided to pull out my USDC.  The exchange rate had changed to
1.002328 b-USDC for each USDC. 

The system gave me back:
1.002328 * 498.9582 = 500.1197 USDC

So in reality my interest earnings for the 5 day period should be 12 cents.

But instead, the system is simply considering b-USDC to essentially be the same as USDC and thus calculating my interest earnings to be:

500.1197 USDC - 498.9582 "USDC",

or $1.16 in interest for that 5 day period.

Since the b-USDC exchange rate will forever be monotomically increasing relative to USDC,  this problem will get worse with time. It seems like a good answer might be to explicitly handle the basset conversion as just another swap and let the tax package like koinly deal with the cost basis tracking / earnings calculation. Not sure.

**Comment by jumperavocado** [comment]
Thanks for the report, completely missed this. Unfortunately there's no straight forward solution. The lending app state does not have information about the cost basis, and adding the b-asset swap to Koinly would create a taxable event (plus it won't have pricing data for the b-asset). This means we would have to track the cost basis ourselves across all the account history.

For the time being unfortunately I'll have to just remove the INCOME row, and push the long term solution to the back of the work queue.

**Comment by tonyhong8** [comment]
Thanks. One perspective - I ended up handling this as a swap with the b-asset because I figured that technically, that's exactly what is happening on the blockchain; the USDC is exchanged for b-USDC which enters my wallet, before the b-USDC gets staked in an immediately following transaction. 

The fact that the USDC is getting exchanged for b-USDC and thus creating a taxable event doesn't really bother me because I assume that USDC always maintains parity with $1 and thus no gain or loss will occur when exchanged with the bUSDC.  

The pricing of the b-USDC is automatically determined by the exchanged quantity with the $1 USDC for both the swap into and back out of b-USDC.  So Koinly can figure out the cap gain.

As an American, I actually benefit from this interpretation as well, because if I hold the bUSDC for long enough, it can get realized as a long term capital gain. 

Anyway, that's one take. Thanks for the great work with stake.tax!

**Comment by jumperavocado** [comment]
No worries, thanks again for the feedback!

What you suggest is a good workaround for USDC and USDT, but the problem applies to other b-assets as well. When you lend ALGO, if we use a swap to b-ALGO, the realized profit or loss could be significant. Ideally I'd like to implement a general solution for all interest accruing assets (Algofi b-assets and Folks f-assets).

**Comment by jumperavocado** [comment]
Fixed this for Algofi lend&earn stake, working next on adding interest transactions for regular lending as well.
