### ISSUE TITLE
RPC data processing missing memo on IBC transfers

### ISSUE THREAD

**Issue by mbolesta** [hodgerpodger/staketaxcsv#253]
Not critical but another regression I noticed switching to the RPC data is the memo no longer gets populated in the koinly format.

In particular it was an IBC transfer from osmosis to juno. The relayer was set in the memo previously.

**Comment by hodgerpodger** [comment]
Bug probably still exists for CSVs with RPC data source.  So will keep this open.

Good news is only CSV with RPC data source now is BLD and DVPN.
  - mintscan api data source: AKT/ATOM/EVMOS/JUNO
  - LCD data source: the rest of cosmos-based

Confirmed evmos ibc transfer with memo is preserved into koinly CSV format today.

**Comment by hodgerpodger** [comment]
Closing older issues without action.
