### ISSUE TITLE
[TERRA][LP] ASTRO-UST LP

### ISSUE THREAD

**Issue by fentas** [hodgerpodger/staketaxcsv#26]
I have/had a problem with astro lp which is curious because on https://stake.tax it is **working**.
Here is the astro-ust lp contract

[terra17n5sunn88hpy965mzvt3079fqx3rttnplg779g](https://lcd.terra.dev/wasm/contracts/terra17n5sunn88hpy965mzvt3079fqx3rttnplg779g)

and locally it will not be recognized as it has no `init_hook` nor `staking_token` which will be looked up here
https://github.com/hodgerpodger/staketaxcsv/blob/main/src/terra/util_terra.py#L271-L280

if I extend the if-else with
```python
    elif "mint" in init_msg:
        address_pair = init_msg["mint"]["minter"]
        currency1, currency2 = _lookup_address(address_pair, txid)
   ```

it works. :female_detective:

**Comment by hodgerpodger** [comment]
Hm I do confirm that it doesn't work locally for first random example for
astro-ust lp contract.  No idea what's happening on stake.tax without the
specifics of particular address.

I'd say add this fix as PR if you're willing and able?  Fix looks great!
  * I confirmed the fix works for an example locally and can run it through
private tests later not available in the public repo.
