### ISSUE TITLE
Add Support for Cointracking.info new Liquidity Pool Transactions types

### ISSUE THREAD

**Issue by KeinNiemand** [hodgerpodger/staketaxcsv#260]
Cointracking now supports special transaction types for liquidity pool transaction (both for in, out and LP rewards) stake.tax should have an options to properly export LP transaction for cointracking using these new transaction types.

**Comment by zedanee** [comment]
In my last tax report i tried to use these LP types, but i reverted back to treat LP transactions as trades. I guess this is the way to go especially for german taxes. At least we will need additional information here in how this feature will interact with the treat lp deposits/withdrawals as option.

**Comment by pbennett** [comment]
LP trades are tricky - adding liquidity to a pool really shouldn't be a trade per-se, but just putting into a pool - and then upon withdrawal the extra fees gained would be additional tokens, as income, w/ cost basis set upon withdrawal.  Every country will vary but at least in the US, guidance is poor to nonexistent.

**Comment by hodgerpodger** [comment]
Fixed and deployed today with https://github.com/hodgerpodger/staketaxcsv/commit/894a8ef876fa35736ccbb2f7b4ab0c3857bb1e93
