### ISSUE TITLE
Add an option to tread LP deposits/withdrawls as trades

### ISSUE THREAD

**Issue by KeinNiemand** [hodgerpodger/staketaxcsv#29]
Some contries treat LP deposits and withdrawls as selling the coins/token you put into the LP and buying LP token (gamm x in case of osmosis). RIght now LP withdrawls/deposites are either threaded as a non exportable special transaction or as simple transfers an opton to thread them as trades between LP tokens and the token you put in / pull out of an LP would be usefull.

**Comment by hodgerpodger** [comment]
will add this week

**Comment by hodgerpodger** [comment]
added with https://github.com/hodgerpodger/staketaxcsv/commit/bf27b4404481eb9fe3c4fd4e27c1e9976ab84c51 and deployed
