### ISSUE TITLE
report_stride.py

### ISSUE THREAD

**Issue by digidoc2** [hodgerpodger/staketaxcsv#295]
I am a beginner with programming, is there a way I can easily create a report_stride.py file for the stride format?

**Comment by hodgerpodger** [comment]
Ah, I wrote this up just now for those interested in something like that: https://docs.stake.tax/devs/adding-csv-in-cosmos-based-ecosystem

**Comment by digidoc2** [comment]
Thanks, we renamed & copied everything from KYVE to STRIDE and got a csv. Unfortunately we also got 120 errors like this:
---
INFO:root:Requesting url https://stride-api.polkachu.com/cosmos/tx/v1beta1/txs?page=1&limit=100&order_by=2&events=transfer.recipient%3D%27strideXXXXXXXXXXXXXXXXXXXXXXXXXX%27 ...
INFO:root:{'message': 'Processing 120 transactions... '}
ERROR:root:_amount_currency_from_raw(): no case for amount_raw=118986289449001773, currency_raw=staevmos
---
Would it help to provide you with more information? Would you know what mistake might cause this error message? Maybe a formatting issue? How can we resolve this?

Thank you very much!

**Comment by hodgerpodger** [comment]
Ah, you need to add a case in _amount_currency_convert() in https://github.com/hodgerpodger/staketaxcsv/blob/main/src/staketaxcsv/common/ibc/MsgInfoIBC.py .

I think I'm going to close this issue.  You can ask further questions in the discord.
