### ISSUE TITLE
Solana: staking rewards missing

### ISSUE THREAD

**Issue by dustyberry1** [hodgerpodger/staketaxcsv#3]
This is really great and useful. There’s a note in the docs about staking rewards that are missing:

> Note to SOL stakers: If you close a staking account, your rewards history will not appear in the CSV.  However, this is recoverable.  You simply need to re-create the staking account(s) (i.e. create stake account 1, stake account 2, etc. and no need to delegate).

How exactly does one go about doing this? Thanks

**Comment by hodgerpodger** [comment]
Ah basically you want to (re)create a staking account within your wallet application.

For solflare, this is under https://solflare.com/staking -> CREATE ACCOUNT.

For phantom wallet, looks like ... you may not be able to do this action.  Hm didn't realize this.

**Comment by dustyberry1** [comment]
Yeah I am using Phantom. I staked again with same validator but it created a different stake account so the previous history is still lost. Oh well

**Comment by hodgerpodger** [comment]
Ah darn, didn't know that.  If you'd like, I can take a look at your bookmark url or wallet address if you DM @staketax or support@stake.tax .  It's probably something I can fix (over time; maybe not immediately).

**Comment by hodgerpodger** [comment]
Deployed a fix today.

Details: fix gets staking rewards for inactive staking accounts.

https://github.com/hodgerpodger/staketaxcsv/commit/22a80ba46204acd1dd973b2b166955f4915de104
