### ISSUE TITLE
I try to fetch data from Cosmos (ATOM), but I only get date 1.5 years back, not 3 years.

### ISSUE THREAD

**Issue by martinkrung** [hodgerpodger/staketaxcsv#305]
hi

This address doesen't import anything and has tx 3 year back:

https://www.mintscan.io/cosmos/account/cosmos1pv6s6z542kyudwq8zxznkeu6hm6yv4fgvpzvd3

![Screenshot at 2023-05-02 17-43-46](https://user-images.githubusercontent.com/918180/235716756-3a15068b-8628-4daf-b43d-feb31f104734.png)

On my address, I did not a single tx in 2020, maybe thats the reason the import stops.

**Comment by hodgerpodger** [comment]
Ah, this is a known limitation of the current codebase.  It relies on the history of the node, which only goes back so far.

**Comment by hodgerpodger** [comment]
Release new version of ATOM CSV today, with much longer history.
