### ISSUE TITLE
ATOM: Server Error

### ISSUE THREAD

**Issue by acates1982** [hodgerpodger/staketaxcsv#306]
I've been trying for a few days now and constantly receiving an ATOM: Server Error when trying to retrieve ATOM transactions. Having no issues with others, specifically SOL. 

Response from https://prodapi.stake.tax/txs is:

`{"success": false, "error_type": "INTERNAL_ERROR", "message": "internal error"}`

![Screenshot 2023-06-09 at 3 15 16 PM](https://github.com/hodgerpodger/staketaxcsv/assets/18124185/0ab2ff83-f878-4742-a3d1-92a6e37c346d)

**Comment by hodgerpodger** [comment]
Alrighty, I switched the rpc node to something with less history than the original, but at least there's a CSV now on the website.
