### ISSUE TITLE
pysha3 is unmaintained and has a security vulnerability

### ISSUE THREAD

**Issue by yawhide** [hodgerpodger/staketaxcsv#307]
howdy,

I noticed that this project is using pysha3 which has a security vulnerability. 
see https://github.com/tiran/pysha3/issues/29 & https://github.com/advisories/GHSA-6w4m-2xhg-2658
unfortunately pysha3 is archived and unmaintained.

does this repository require pysha3? I did a search in the codebase and couldn't find any usage of it. can we remove it as a dependency?

thanks

**Comment by yawhide** [comment]
@hodgerpodger bump on this question! thanks

**Comment by hodgerpodger** [comment]
fixed via https://github.com/hodgerpodger/staketaxcsv/commit/13ee9c56df00ff39a7475b0e5f98f1b414e76633
