### ISSUE TITLE
ALGO reporting doesn't work

### ISSUE THREAD

**Issue by friggingee** [hodgerpodger/staketaxcsv#314]
When entering any ALGO address, the app returns a server error without further details.

```
curl 'https://prodapi.stake.tax/txs' \
  -H 'authority: prodapi.stake.tax' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,de;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://stake.tax' \
  -H 'pragma: no-cache' \
  -H 'referer: https://stake.tax/' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Brave";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  --data-raw '{"ticker":"ALGO","wallet_address":"5R3KKP4BNXCMSWNP76OOK5HEAYVQODJBLNCX4YZQPTYDIZJVM6NTOBLDFI","options":{}}' \
  --compressed
```

yields:

`{"success": false, "error_type": "INTERNAL_ERROR", "message": "internal error"}`

**Comment by hodgerpodger** [comment]
Oops, I forgot to update a planned setting change. I'll fix tonight.  Thanks for the report.

**Comment by hodgerpodger** [comment]
Hm tried the update.  But looks like there's another issue I wasn't aware of.  So still working on this.

**Comment by friggingee** [comment]
> Hm tried the update. But looks like there's another issue I wasn't aware of:
> 
> * All addresses show "Wallet address not found" on the website, which likely means `wallet_exists` function in report_algo.py always returns false.
> 
> So I'll likely need a bit more time to figure this out.

Was just about to report the follow-up ;) But yeah, something's still off.

**Comment by cooleydw494** [comment]
Hmm. I was going to use this and saw this issue and thought "hey I know some python I'll see if I can help out and maybe make a PR!"

Checked out the python algorand SDK and the "account_exists" function isn't documented xD

Checked the specific version from requirements.txt too, in case you were wondering. I am cry.

**Comment by jumperavocado** [comment]
> Checked out the python algorand SDK and the "account_exists" function isn't documented xD
edit: to be clear, "wallet_exists" calls indexer.account_exists and I was assuming the indexer is the one from the python algo sdk

We are not using the algo sdk for this, just the REST API, see [src/staketaxcsv/algo/api/indexer.py](https://github.com/hodgerpodger/staketaxcsv/blob/main/src/staketaxcsv/algo/api/indexer.py)

> All addresses show "Wallet address not found" on the website, which likely means wallet_exists function in report_algo.py always returns false.

Seems to work locally, is this possibly staketax's IP being throttled or even banned by the node provider?

**Comment by cooleydw494** [comment]
That is actually pretty good news because I really need to use it. I'll try it locally tonight. And if its a throttled/banned IP issue I guess there's no point in me looking into helping to fix it anyway. Crappy.

**Comment by dukecc82** [comment]
just had the wallet address not found issue.   Came here and saw this.   Running this locally works fine?

**Comment by dukecc82** [comment]
verified it works great locally.

**Comment by jumperavocado** [comment]
I'll see if I can make a GUI app for this when I get some free time so people have an easier way to run this locally. We've had issues with node throttling before, especially during tax season.

**Comment by hodgerpodger** [comment]
Apologies for the delay in addressing this (wasn't feeling the greatest last couple of weeks).  Thanks for the work and patience everyone, especially @jumperavocado .

There was a deployment/environment bug that always existed but didn't come to fruition until I tried changing a setting ( specifically STAKETAX_ALGO_INDEXER_NODE).  Fix is deployed to stake.tax.
