### ISSUE TITLE
LUNA1 API (Luna Classic) is failing with an 'internal error' message.

### ISSUE THREAD

**Issue by p00595** [hodgerpodger/staketaxcsv#316]
LUNA1 API (Luna Classic) is failing with an 'internal error' message.

My Luna Classic wallet address is: https://finder.terra.money/classic/address/terra17h2a42sf7kv0mrzqce90lhjvlrxtch5vw5hps4

**Comment by grossamer** [comment]
I am having the same issue

**Comment by conor-neary** [comment]
Same

**Comment by zedanee** [comment]
it seems that the default node is redirecting to  https://terra-classic-lcd.publicnode.com
and that gives us :
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error","data":"Failed to parse the request body as JSON"},"id":null}

is there any other public node we can use ?

**Comment by hodgerpodger** [comment]
Thanks for the info and notifications @p00595 @conor-neary @zedanee @kylemanna .  Fix is in today on stake.tax.   

https://github.com/hodgerpodger/staketaxcsv/commit/f99193017e4739f7c22f61890270913e57c74df8


It's a bit of a temporary fix (basically just omits call to lcd api for txs method ) in that progress bar no longer works but figure it's better to have a CSV with incorrect progress than no CSV at all.  Will need subsequent fix to get progress bar correct.

**Comment by p00595** [comment]
Hello @hodgerpodger,
Thanks for looking into this.
It's now partially working for me, but till fails with an 'internal error' after processing to about 96%.
Could you please look at my job that is failing still?

Job bookmark: https://stake.tax/?jobId=8a907c5992334f26af62f6b61c4dd440
Wallet address:  terra17h2a42sf7kv0mrzqce90lhjvlrxtch5vw5hps4

Thanks and regards,
Calvin Chan

**Comment by hodgerpodger** [comment]
Ah okay. Looks like the terra blockchain upgrade changes multiple lcd api methods.  So subsequent fixes needed unfortunately.  Still work in progress.

**Comment by p00595** [comment]
Hello @hodgerpodger,
Just checking in to enquire as to whether any further progress has been made towards resolving the issue?
Thanks and regards,
Calvin Chan

**Comment by p00595** [comment]
I downloaded the staketaxcsv source code to my Windows computer and ran it from the CLI interface.
It appears to fail because  a contract cannot be found in the CONTRACTS dictionary (i.e. Not found in folder 'staketaxcsv\src\staketaxcsv\luna1\col5\contracts')
The stderr.txt and stdout.txt command output files are attached.
[stderr.txt](https://github.com/hodgerpodger/staketaxcsv/files/13412370/stderr.txt)
[stdout.txt](https://github.com/hodgerpodger/staketaxcsv/files/13412371/stdout.txt)

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by hodgerpodger** [comment]
Should be fixed now.  Several fixes over the last month for LUNA1.
