### ISSUE TITLE
Trades on OSMOSIS show up as transaction type_UNKOWN

### ISSUE THREAD

**Issue by KeinNiemand** [hodgerpodger/staketaxcsv#317]
Recently when I export my osmosis transaction use stake.tax, new swaps/trades show up as two or more transaction transaction type _UNKNOWN and then don't show up at all when I import them into cointracking. Older trades still show up as trades but newer ones don't.

Please fix the exports for trades on osmosis.

**Comment by hodgerpodger** [comment]
Several fixes/updates for newer types of transactions for osmosis, especially swap.  There's still more newer types not supported yet due to complexity when reading the explorer, but simply open up new github issue, and I should be able to take a look.
