### ISSUE TITLE
[Request] Add support for Jupiter limit orders

### ISSUE THREAD

**Issue by giles-t** [hodgerpodger/staketaxcsv#328]

**Comment by giles-t** [comment]
Hello!

Support for Jupiter DCA's is amazing. Extension of this to support limit orders would be incredible.

Thanks!

**Comment by hodgerpodger** [comment]
Any chance anybody can provide the program ID for Jupiter limit orders or any example transaction?

**Comment by giles-t** [comment]
Looks like this is the program ID `jupoNjAxXgZ4rjzxzPMP4oxduvQsQtZzyknqvzYNrNu ` / https://solscan.io/account/jupoNjAxXgZ4rjzxzPMP4oxduvQsQtZzyknqvzYNrNu

From here: https://station.jup.ag/docs/additional-topics/links-and-contract-addresses

**Comment by hodgerpodger** [comment]
Fixed and deployed today with https://github.com/hodgerpodger/staketaxcsv/commit/fa8da78f823d3c7802ba1b56a87abc13f04938aa

**Comment by giles-t** [comment]
Sorry to reopen but after giving this a go limit transactions are still being reported as unknown. I tried to dig in a little and it seems they are being labeled properly in `handle_jupiter_limit.py` but not grouped correctly as trades.
