### ISSUE TITLE
support for multi route trades on osmosis

### ISSUE THREAD

**Issue by zedanee** [hodgerpodger/staketaxcsv#330]
since there are superfluid pools, some trades are multi route trades that
have more than one pool involved. Currently transaction type is unknown. The most
common trading pair seems to be ATOM / OSMO but it also occurs on others like
MARS, CRO, WBTC

**Comment by zedanee** [comment]
i checked some other wallets and some of them seem to be supported. I'm having problems with pairs
e.g. CRO/axlUSDC , TIA/axlUSDC, QSR/REGEN

**Comment by hodgerpodger** [comment]
Hello - I'm looking for an example transaction. If you'd like to remain anonymous (as I do as well), any contract address would as well. 

Thanks.

**Comment by hodgerpodger** [comment]
Oops, forgot to tag @zedanee

**Comment by hodgerpodger** [comment]
okay I just fixed a case where there's intermediate transfers that result in tiny net amounts of extra tokens, which cause problems in the parser.

Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/5e673b11d0f7f8bfd99886bb9365cf0a842dfb00 .

I think there's a good chance this is the fix.  Reopen if still seeing an issue.

**Comment by zedanee** [comment]
Hi Thanks for the reply,

sure i am a litte cautious with my own transactions . Not wanting to release them public with my name attached :-)

I guess you almost fixed it. only  a few axlWBTC did't work and they are measured in satoshies , i added currency, _ = currency_raw.split("-satoshi") 
one 1135 ,1090 worked but the other 1090, 1135 did not , strange , i need to git pull tomorrow and have a look at your changes.
I found another one 725 ,1135 that was still unknown and 1135 ,1060 .. 

I found a whale address by just looking at some blocks and this has even better examples than my own
because he or she ? also changes exposure and ranges withing the pools. Have a look at it osmo1n93lzalurfdadx43486s46luyph4497ukqncav

my own address has more unknown trades, i'll try to find other examples of trades that, are not recognized. 

Don't hesitate to ask for more, I'm active in the cosmos ecosystem, but your code is hard to grasp for me. I'm a
Perl guy, but I have it running in a docker container and am able to modify and extend things and i'm fammilar with git.

Your project helped me a lot with my taxes, i will try to support you as much as i can.

Regards,
Lars  

 
 

Gesendet: Samstag, 13. Januar 2024 um 22:11 Uhr
Von: "hodgerpodger" ***@***.***>
An: "hodgerpodger/staketaxcsv" ***@***.***>
Cc: "zedanee" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [hodgerpodger/staketaxcsv] support for multi route trades on osmosis (Issue #330)


 

Hello - I'm looking for an example transaction. If you'd like to remain anonymous (as I do as well), any contract address would as well.

Thanks.
