### ISSUE TITLE
SOL --> Koinly import not working anymore 

### ISSUE THREAD

**Issue by coreworx** [hodgerpodger/staketaxcsv#332]
Hi,

Koinly import for SOL does not seem to work anymore. It was working a couple of days ago.

Koinly error message on import:

file must have these headers: ID (read-only),Date (UTC),Type,Tag,From Wallet ID,From Amount,From Currency,To Wallet ID,To Amount,To Currency,Fee Amount,Fee Currency,Net Worth Amount,Net Worth Currency,Fee Worth Amount,Fee Worth Currency,Deleted,TxSrc,TxDest,TxHash,Description

Job link:
https://stake.tax/?jobId=922aa93847904c7b9808c0d1106f6a10

Thanks!!

**Comment by coreworx** [comment]
Those are the headers which are present in the Koinly csv from stake.tax:
Date,Sent Amount,Sent Currency,Received Amount,Received Currency,Fee Amount,Fee Currency,Net Worth Amount,Net Worth Currency,Label,Description,TxHash

**Comment by hodgerpodger** [comment]
Thanks for the report!  Will get on it ASAP

**Comment by hodgerpodger** [comment]
Just tried that wallet.  Koinly import seems to be fine (just one error saying currency not found; but that makes sense).  Perhaps downloaded the wrong CSV?

**Comment by hodgerpodger** [comment]
Perhaps a chance koinly is doing some sort of rolling release.  Anyhoo, if any more folks encounter this, please let us know so I know where to look.

**Comment by coreworx** [comment]
Thanks for looking into it. 
Yes, that's what i thought too, that i was downloading the wrong csv, but then i did it again and made multiple downloads, I also used different browsers (Edge, Brave, Chrome).
I will try it again now and will let you know, if it works or not.

**Comment by coreworx** [comment]
koinly-20240203-064435.csv has been imported
Now it is working, maybe there were changes in the koinly backend while i was trying it.
Many thanks for your time!
