### ISSUE TITLE
Enhancement Request - Multi-chain retrieval on Cosmos+ tab

### ISSUE THREAD

**Issue by bigshooTer39** [hodgerpodger/staketaxcsv#334]
I spend a significant amount of time downloading my transactions chain by chain...   

Requesting an enhancement to Cosmos+ tab to add the ability to enter multiple addresses + endpoints to pull multiple chains all at once. 
It would be amazing if we could enhance stake.tax to either to pull trx for mulitple chains at once, either in parallel or in sequence.  Individual csv's are fine as a phase 1.  Consolidated would be preferred but individual csv files would be better than manually downloading each one.

**Comment by hodgerpodger** [comment]
Good idea but wasn't sure how to present this as to be that useful.
