### ISSUE TITLE
Connect wallet. Use wallet's RPC endpoints.

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [hodgerpodger/staketaxcsv#335]
Wouldn't it be awesome if:

1.  I could connect my Web3 wallet to this webapp? and
2.  The webapp used the wallet's linked RPC endpoints for its data collection? and
3.  The webapp used the web3 wallet API to learn which chains contain transactions? and
4.  The webapp, if locally hosted, could remember which transaction(s) it had already exported on previous runs?

These things would be marvelous.

**Comment by hodgerpodger** [comment]
I agree these would be nice.  Perhaps one day in the distant future.  For now unlikely.
