### ISSUE TITLE
[Bug] Jupiter Limit Orders are still marked as "unknown" after support was added

### ISSUE THREAD

**Issue by giles-t** [hodgerpodger/staketaxcsv#337]
Jupiter Limit Order were added in #328 but are still being marked as `unknown`

I tried to dig in a little and it seems they are being labeled properly in handle_jupiter_limit.py but not grouped correctly as trades.

**Comment by hodgerpodger** [comment]
I spot checked 2 random accounts with limit orders, and it seemed to be okay.  So I probably need more info to identify where the problem occurs.  Some ideas:

- is it all the trades are marked unknown for this account or just some of the trades?
- any random sample you can find would be great.

**Comment by hodgerpodger** [comment]
Thanks for tracking that info down @giles-t .

Added a fix for additionally handle partially filled limit orders (jupiter limit txs).  

Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/7b4e3668afccdf6a387d0ccd3ad93027bc8c87b8
