### ISSUE TITLE
Add support for Neutron

### ISSUE THREAD

**Issue by phy-chain** [hodgerpodger/staketaxcsv#341]
I've been using your app to import missing data from Cosmos into Koinly, and I have to say, it's really great and works most of the time.
Though Im having trouble importing Neutron data. Your app logs 11 lines for my wallet, I get 4 rows when I export, but when I check on [explorer](https://neutron.celat.one/neutron-1), I can see 50 lines . What am I missing ?
Most txs on Neutron are votes, some IBC transfers, some liquidity on Astroport with ATOM LP

**Comment by hodgerpodger** [comment]
Thanks for inquiring.  i'm guessing you're talking about the cosmos+ tab.  You're not really missing anything, other than each LCD endpoint has varying amounts of historical data available.  Default behavior now seems to be to truncate history in the cosmos ecosystem.

Good news is I plan to integrate Neutron to the website soonish so stay tuned.
