### ISSUE TITLE
Borrowing and returning funds on Mars is not tracked correctly

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#345]
Example: https://www.mintscan.io/osmosis/tx/DDCE150A367B7D533C4E2DAC8913F509FE67E949A22B9403F94ED134FFD7384C

Complete job: https://stake.tax/csvapp/d42f5e6cedb645fdb464e43a123f98f3#

How it should be: https://support.koinly.io/hc/en-us/articles/9918467633564-Crypto-loans-repayments-and-collateral-CDP

**Comment by p0mvn** [comment]
Another example: https://www.mintscan.io/osmosis/tx/E9CBC71972A0FA5CE5FF91E379F1336D759D0DF23A86B01A334003CF268BAC1F

**Comment by p0mvn** [comment]
Repayments also do not get picked up. Example:
https://www.mintscan.io/osmosis/tx/A1611D76479EA5120133702D8B8AECC3CCC08C53ED848AC6DDC14BA15C56D166

**Comment by hodgerpodger** [comment]
Fixed to add borrow/lend/repay labeling for all mentioned cases above.

This is likely not comprehensive for all cases and user desires (lending not natively supported for import/export for koinly/cointracking/etc as far as I can tell).

note: looked at example of AAVE, which uses "atokens" (analogous to treatment of osmosis liquidity pool deposits I think in terms of how it looks in koinly/cointracking/etc).   For Mars lending, I'm not sure how to treat (there's perhaps "debt_shares_added" field but still unclear).
