### ISSUE TITLE
Swap on Raydium Liquidity Pool V4 not showing up correctly in CSV, shows as _unknown and token changes are not shown

### ISSUE THREAD

**Issue by N11cK** [hodgerpodger/staketaxcsv#347]
Swap on Raydium Liquidity Pool V4 not showing up correctly in CSV, shows as _unknown and token changes are not shown
example: https://solscan.io/tx/3w5VuMmyaYXq4gK2bQGj16gGp5JfCR6V8nkTovYYRWtfc3CBXWhq6N3mk8TMqLB5y5rH3sRzH1rNsgcPmLAuqarg

**Comment by hodgerpodger** [comment]
Thanks for the report.  Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/e841f46a0ac390ab1905564c1da126e30c840035
