### ISSUE TITLE
Fails to parse Mars ClaimRewards on Osmosis

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#351]
Steps to repro:
- TX: https://www.mintscan.io/osmosis/tx/9B91BA139878FDA36BCD23039AEA5C23AED3AD278FB439F13BB8B00BD0D8439B
- Account: osmo1hw4c4f7005mv8jgguztztwu9f8e5qyutr7v2ar

Notice it is unknown in the report:
![image](https://github.com/hodgerpodger/staketaxcsv/assets/34196718/d730b311-a405-48cc-ad7b-1b91786722ab)

Job: https://stake.tax/csvapp/cb296d9d872b44f49178ff5b6f528c16#

Would really appreciate help with getting this fixed 🙏

**Comment by p0mvn** [comment]
Another example: https://www.mintscan.io/osmosis/tx/F7079B1AD90EECF639EC9787C9F1887172095CA054D1ACBA02440C045B714110

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/6ae615b73283ff9ff610c4cd842ed4b0c2a27dfe
