### ISSUE TITLE
Fails to recognize Contract-Deposit messages for Mars on Osmosis

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#352]
Example: https://www.mintscan.io/osmosis/tx/E29DC7B56597DCF95BEEF89FABB14493E03C45B9DB22E2332E28AA275D574C4A

Screenshot: 
![image](https://github.com/hodgerpodger/staketaxcsv/assets/34196718/6bb92584-967f-47a1-81a0-f8154a2fd2e1)

Job: https://stake.tax/csvapp/cb296d9d872b44f49178ff5b6f528c16#

Would appreciate help with resolving these 🙏

**Comment by hodgerpodger** [comment]
This is like a borrow transaction?  Any info would be great, since I'm not intimately familiar with all the ecosystems.

**Comment by p0mvn** [comment]
As far as I understand, Mars has a concept of credit accounts.

Users deposit funds into a credit account which they can then lend to other users.

There's also an opportunity to use their credit account value as collateral for borrowing.

This particular transaction is about depositing into a credit account.

Thank you for looking into this!

**Comment by hodgerpodger** [comment]
Fixed (treated as transfer)
