### ISSUE TITLE
Fails to recognize loan repayments with Mars v2 on Osmosis

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#353]
Example transaction: https://www.mintscan.io/osmosis/tx/47EE8B7A7B22F8458E73FD34E2D2A273ABA405FBF1FBFF020F3D54EBBC1F40EA

**Comment by hodgerpodger** [comment]
Added support for mars credit manager repay.  Somewhere around https://github.com/hodgerpodger/staketaxcsv/commit/8fe9b52248a3ffa034140129acb2d26781489b85.
