### ISSUE TITLE
Osmosis Concentrated Liquidity Positions Fail to Get Processed

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#354]
Examples:
- AddToPosition https://www.mintscan.io/osmosis/tx/15AFDC2E938CAF37A5D39A1955E91384E622DA3B0AA2EB4A93999E25534703FB
- CreatePosition https://www.mintscan.io/osmosis/tx/E2FDA5E608D0C1D6D155D9CC0DA1CAE80EA5CBB871B2DD138272AEDF73C20C7D
- WithdrawPositio https://www.mintscan.io/osmosis/tx/3967ED2E3D8F5C0A0CB5D7C0E9443633C11BA235933301A2CDD2C2C0A71E624E

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/3c3dcc3d777a1d018e19548c8df31e2cf4ed45fd
