### ISSUE TITLE
Quasar Vault Claim Reward Transactions Do Not Get Processed

### ISSUE THREAD

**Issue by p0mvn** [hodgerpodger/staketaxcsv#355]
Example: https://www.mintscan.io/osmosis/tx/8627025DE1CB8D549EBD25A12BB04ABBC8281789D9004FE90A941BEC8D084C3F

**Comment by p0mvn** [comment]
Here is an example redemption:
https://www.mintscan.io/osmosis/tx/0EA265F5009DA0DD60E86E5250587590193DFEA63095812C7EBBFA9DD77225E4

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/3e0e97fb442d9263d2a9e6659af2a1532a76a4fd .

Thanks for reporting.
