### ISSUE TITLE
Luna2

### ISSUE THREAD

**Issue by hpatner** [hodgerpodger/staketaxcsv#356]
I keep getting an error when I try for the transactions in Luna2. Is it still supported?

**Comment by hodgerpodger** [comment]
Thanks for the report.  Yup, been working on it since yesterday.  A couple protocol or data changes to the terra blockchain is causing issues but looks to be fixable.  Just taking a little time.

**Comment by hodgerpodger** [comment]
Oi, new error popped up within last 2 days for Luna2 CSVs unfortunately (Terra 2.0).  Deprecation of TFL infrastructure potentially, which is very not good for Luna2 CSVs ...
