### ISSUE TITLE
Terra Classic (LUNC, Terra 1.0, columbus) support fails to correctly calculate LUNC and USTC reward amounts.

### ISSUE THREAD

**Issue by p00595** [hodgerpodger/staketaxcsv#357]
The stake.tax Terra Classic (LUNC, Terra 1.0, columbus) support fails to correctly calculate LUNC and USTC reward amounts for txns more recent than 9th Feb 2024 and possibly earlier than that for import into Koinly.
NB 1: It does report some LUNC and USTC reward amounts but the amounts are only a very small fraction of the actual amounts.

NB2: My wallet address is: terra17h2a42sf7kv0mrzqce90lhjvlrxtch5vw5hps4

Regards,

Calvin Chan
Email: calvinchan@planetchan.com

**Comment by hodgerpodger** [comment]
Thanks for the reports. Might take a little time but I'll get to this issue.

**Comment by p00595** [comment]
Thank you, I greatly appreciate you looking into this as tax time here in Australia is at the end of June 2024.
I have been in contact with Koinly over the past 12 months in an attempt to get their LUNC API support working properly. They did spend time on it but gave up completely around the 9th Feb 2024, suggesting I instead generate a CSV file using stake.tax or trackterra.org and import that into Koinly.
Trackterra.org however seems to be even more broken, hence Stake.tax is possibly the last remaining viable solution.

NB: My wallet address is: terra17h2a42sf7kv0mrzqce90lhjvlrxtch5vw5hps4

**Comment by hodgerpodger** [comment]
Alrighty, added one key fix to add support for new text in certain withdraw reward transactions.

**Comment by p00595** [comment]
Hello @hodgerpodger,
The good news: The LUNC and USTC rewards now appear to be calculating as expected. Thanks for fixing that so quickly.
And the bad news: The generated CSV is now incorrectly reporting that I have thousands of WBNB coin rewards worth millions of dollars.
I wish it were true, however I'm am not that good of an investor.
Could you please look into why stake.tax is now doing that?
