### ISSUE TITLE
Terra Classic (LUNC, Terra 1.0, columbus) support fails to correctly calculate WBNB reward amounts.

### ISSUE THREAD

**Issue by p00595** [hodgerpodger/staketaxcsv#358]
Terra Classic (LUNC, Terra 1.0, columbus) support was previously incorrectly calculating LUNC and USTC reward amounts.
As of today that problem has been fixed by stake.tax development support, however the fix seems to have introduced a new bug in which the  generated CSV is reporting WBNB reward amounts worth millions of dollars which is not correct as the actual amounts should only be worth a few cents at most.
Could you please look into resolving this new problem.

**Comment by hodgerpodger** [comment]
Thanks for the report.  Is this a different address than previous github issue reported?  I'm not seeing any WBNB rewards at the moment.

**Comment by p00595** [comment]
My wallet address is: terra17h2a42sf7kv0mrzqce90lhjvlrxtch5vw5hps4

And attached is a copy
[koinly-20240604-022420-lunc.csv](https://github.com/user-attachments/files/15541754/koinly-20240604-022420-lunc.csv)
 of the CSV generated by stake.tax showing the excessively large WBNB staking rewards.

**Comment by hodgerpodger** [comment]
Fixed and deployed.

Thanks for the report and info.

**Comment by p00595** [comment]
Thank you once again for a very prompt fix. I have not checked the results with  fine toothed comb, but it appears to be calculating reward amounts correctly now.
