### ISSUE TITLE
Anchor Earn received amount wrong

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#36]
Hi, I think I found a new issue with the cointracking.info format.
In Terra, when withdrawing from anchor earn, the actual amount in buy should be 998.73536335 instead of 1000.000035
<img width="498" alt="anchor earn withdraw" src="https://user-images.githubusercontent.com/20350385/149682121-1f54fe7a-1ee7-4285-a736-9ba7d39b01c0.png">

When you withdraw from anchor there are 2 transactions from the requested amount (1,000.000035).
Receiver 1 (Fee Collector): 1401465uusd
Receiver 2 (your wallet): 998598570uusd <- you don't actually get this amount in your wallet. you get this minus the tx fee

What you actually get in your wallet is 998598570uusd - tx fee

<img width="799" alt="actual transaction" src="https://user-images.githubusercontent.com/20350385/149702168-960cdd92-5529-4283-bbde-cc441b4f1c2c.png">

Net deposit/actual received amount (998.73536335)= Requested amount (1,000.000035) - tx Fee (0.250657) - Fee Collector (0.01401465)

**Comment by hodgerpodger** [comment]
Confirmed.  Thanks for these finds.  Will fix this one this week as well.

**Comment by hodgerpodger** [comment]
fixed with https://github.com/hodgerpodger/staketaxcsv/commit/38ae5973c228de8f7f8daadcda2e9451d14c1f5b.  Will note later when deployed

**Comment by hodgerpodger** [comment]
deployed
