### ISSUE TITLE
Stable Coin Swaps on Osmosis

### ISSUE THREAD

**Issue by zedanee** [hodgerpodger/staketaxcsv#366]
Pool Ids:
1,212
Token In:
1.000,000000 
USDC
Token Out:
1.000,000000 
axlUSDC

axlUSDC in USDC(Noble) trade is recognized as type unknown.

Pool Ids:
1260 ,1648
Token In:
1.080,000041295559900000 
axlDAI
Token Out:
1.069,993994 
ibc/44492EAB24B72E3FB59B9FA619A22337FB74F95D8808FE6BC78CC0E6C18DC2EC

USK in axlDAI
Kujira USK is not recognized.

https://finder.kujira.network/kaiyo-1/token/ibc%2F44492EAB24B72E3FB59B9FA619A22337FB74F95D8808FE6BC78CC0E6C18DC2EC

**Comment by hodgerpodger** [comment]
Is this for osmosis or kujira?  I fixed swaps in osmosis semi-recently so perhaps this is fixed.
