### ISSUE TITLE
Cointracking Ticker fixes

### ISSUE THREAD

**Issue by zedanee** [hodgerpodger/staketaxcsv#367]
NTRN->NTRN2
INJ->INJ2

found problem on injective and osmosis export for cointracking

**Comment by zedanee** [comment]
TIA -> TIA3 found on celestia export

**Comment by hodgerpodger** [comment]
Thanks for report!  Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/3e062f9a3f5dcfe4664df4e8b49b8b85be518dcd .
