### ISSUE TITLE
Many entries missing in non-default csv exports

### ISSUE THREAD

**Issue by karthikveeramani** [hodgerpodger/staketaxcsv#4]
If you export as anything other than default csv format (say koinly, zenledger formats), many deposit entries are missing.

**Comment by hodgerpodger** [comment]
Ah, I think you might be referring to transactions with TX_TYPE=_*,  in which case they must be handled by user:
https://docs.stake.tax/faq/faq#1.-why-does-my-balance-in-koinly-cointracker-not-match-my-wallet
Perhaps some better user messaging for this.

If not, you can specify an example TX_TYPE with this issue.

**Comment by karthikveeramani** [comment]
@hodgerpodger These are entries that show up as TX_TYPE_UNKNOWN. They are all NFT transactions (minting that results in deposits, secondary sale royalties from markets).

**Comment by hodgerpodger** [comment]
Ah, probably need specific txid, program, market, or some identifying information.

The way the parser works it is not able to handle nft transactions (there are many across markets/programs) generically unfortunately.
