### ISSUE TITLE
Spectrum Protocol bPsiDP-24m vault not properly handled

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#46]
Spectrum Protocol bPsiDP-24m vault not properly handled

See for example this transaction
https://finder.extraterrestrial.money/mainnet/tx/363D624070FFEB7EE5834C58D52B0ADAE8859C0D957224587816EABF2DE2FBD4

Person deposits 500 UST gets 499.153310 bPsiDP-24m that is now being autocompounded in Spectrum vault.

Transaction shows as UST to aUST
![image](https://user-images.githubusercontent.com/20350385/150738590-e3e39374-b07b-493a-a735-49edb0dc42f2.png)

But transaction in reality has multiple steps
![image](https://user-images.githubusercontent.com/20350385/150738814-97cf7bef-159b-42f2-b1a1-d57041a2f2e6.png)

**Comment by hodgerpodger** [comment]
Just removing issues for which action unlikely to be taken.  Re-add if desired.
