### ISSUE TITLE
LP for spec, mir, m* assets, mine, vkr [...]

### ISSUE THREAD

**Issue by fentas** [hodgerpodger/staketaxcsv#47]
So for all these mentioned above (and possibly more) they use `bond` instead of `provide_liquidity`.
So what currently is happening is that every transaction towards these contracts is recognized as `anchor`.`handle_bond` which fails of cause.

After some debugging and working into the code it seems easiest just to label these as `provide_liquidity`.
It looks like that `handle_lp_deposit` can handle these transactions just fine.

The current solution I found, is not the cleanest (so this issue instead of pull)

`execute_type.py`
```py
# ...
def _execute_type(elem, txinfo, index=0):
    txid = txinfo.txid
    execute_msg = util_terra._execute_msg(elem, index)
    contract = util_terra._contract(elem, 0)
    try:
        addr = util_terra._lookup_address(contract, txid)
    except Exception:
        pass
     
    # ...
    elif "provide_liquidity" in execute_msg or "bond" in execute_msg and len(addr):
        return EXECUTE_TYPE_PROVIDE_LIQUIDITY
    # ...
```

This solution utilizes the fact, I observed so far, is that the only `bond` type tx which has no addr is the anchor bond itself.
But well :shrug:

**Comment by fentas** [comment]
related: #46

I should have also some `bPsiDP` transactions, will try to look them up.

**Comment by hodgerpodger** [comment]
thanks for the find.  If you have any non-spectrum-protocol examples already, it would be nice to have.  

Guessing the non-spectrum-protocol transactions with `bond` would be much faster to fix.

For spectrum protocol transactions, probably need to start write/rewrite a library/parser to handle multiple messages in one transaction.

**Comment by fentas** [comment]
Do you already start something regarding SPEC or other protocols like astroport, apollo, etc?

**Comment by hodgerpodger** [comment]
Initial idea is process all transactions using wasm keyword data if exists, first, message by message.  Wasm data seems to be fairly uniform in newer contracts?  A bit unsure on this but noting this to myself when I can put more time into this.

If I were to do everything again, I probably would have started with message-by-message parser but starting at col4 with few tx types I didn't choose correctly.

**Comment by hodgerpodger** [comment]
also providing a systematic way to key off contract that trumps tx data keyword is highly desirable

**Comment by wengzilla** [comment]
I believe one of my commits has fixed this issue. @fentas do you have a sample transaction I may try?

**Comment by Mylros** [comment]
The transaction I mention in #46 is a SPEC transaction. 
Would that work?

**Comment by fentas** [comment]
sorry, for late response but I really have to get my taxes done so I took some "shortcuts".
I took this advice
 
> For spectrum protocol transactions, probably need to start write/rewrite a library/parser to handle multiple messages in one transaction. So it would be more involved.

https://github.com/fentas/staketaxcsv/blob/main/src/terra/processor.py#L58

I go through every message of each transaction because multiple things can happen here.
Then I just used `extraterrestrial`'s db of contracts (and extended it a little bit) to separate messages to each protocol so that each protocol can decide what to do or do nothing if common request.

I am not through yet, by any length but getting there.

After that I can migrate it to here, if wanted or at least parts of it.

**Comment by fentas** [comment]
Ok, I got my taxes done > 18k transactions and I got close (not 100% but that's ok).
I implemented a couple of protocols.

I try to fix up and clean up some things and create a draft PR as needed for sure some discussions on how to handle things in general. There were a lot of issues with how transactions were handled.

**Comment by hodgerpodger** [comment]
Just removing issues for which action unlikely to be taken.  Re-add if desired.
