### ISSUE TITLE
[Bug] serum transactions are not exported to non default CSVs

### ISSUE THREAD

**Issue by ISO50** [hodgerpodger/staketaxcsv#53]
**Problem**

Serum buy orders (`tx_type = _SERUM_DEX`) that are added to the `default csv` exports are missing in `accointing` and `cointracking` exports.

**Additional Infos**

Maybe related to this, in the default csv export are multiple lines with the same TX  ID for one Serum trade.

**Comment by hodgerpodger** [comment]
Thanks for the feedback. Serum transactions have been worked on pretty extensively, but unfortunately, I was never able to deduce serum trades from blockchain data, only transfer amounts. Most likely, lower-level work within the serum ecosystem needs to be done to make it possible (or more likely, the application(s) you are trading on).

**Comment by ISO50** [comment]
Hi,
I think it was a two part process, first buying and and then claiming the tokens. At least the `default` csv shows this two transactions.

If I understand you correctly the information on blockchain is missing (or at least not easily accessible) to create a relation between these two transactions to convert them into a regular buy/sell order?

**Comment by hodgerpodger** [comment]
Yup, exactly as you said.  There's only deposit/withdrawal information for blockchain wallet transactions.  There's likely blockchain data in serum market queues with the glue information for buy/sell, but an effort like that would probably be its own indexing data product (I'm guessing folks are working on these things but haven't seen them readily available yet).

FYI all this on my part is just educated guesses.  This is just my current non-expert understanding.

**Comment by gitmalong** [comment]
I'm working on a similar project for my private tax purposes but written in Rust. There is one lower hanging but a bit error prone fruit for SerumDex (Immediate or cancel) orders that follow the scheme:
1) IoC place trade order
2) Settle funds
In that case we can assume that the token transfers from 2) back to users wallet are the result of the placed in trade in 1). We are only mistaken if there were previous funds, related to other orders, on the open orders account. 

There are some open issues on SerumDex regarding that data lack but no one really cares:
* https://github.com/project-serum/serum-dex-ui/issues/109
* https://github.com/project-serum/serum-dex/issues/255

Could we at least try to outline the technical aspects we would need to implement to get these trades. From my understanding we have to parse historical EventQueue data.
