### ISSUE TITLE
Receiver address not respected in TRX with multiple token transfers

### ISSUE THREAD

**Issue by ISO50** [hodgerpodger/staketaxcsv#55]
Hi,

here is a [transaction](https://solscan.io/tx/21U1JdjBsHBE3yv1GAc2xJzFt3mLnAHdVhbKXkJAZdT61YEMdsJ2bVBjfqsELnkCq2NuUHTVEeG7MAZWbKfR6VRX) were a program airdropped tokens to different Solana accounts.

This transaction is related to a StarLaunch IDO, the Token distrubution is somtimes correctly recognized by staketax and sometimes missing, but in this case even the wrong amount is booked.

**Reproduce**

Take whatever receiver address you want from the transaction, generate a report, the `SNS` amount will always be the one from the most top action in the transaction. So for the provided transaction it's always ~ `38.91 SNS`

**Comment by hodgerpodger** [comment]
Thanks for nice details.  I should have a fix in pretty soon.

**Comment by hodgerpodger** [comment]
Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/82e556f8becbff3c724eba1c7d929672568a9baf
