### ISSUE TITLE
Add option to set timezones

### ISSUE THREAD

**Issue by KeinNiemand** [hodgerpodger/staketaxcsv#61]
stake.tax always uses uses UTC time however all other data I use in cointracking uses my local time zone. This leads to transactions that are in the wrong order witch leads to wrong results for taxes. It would be really usefull to be able to set your time zone so transaction have the correct time.

**Comment by Mylros** [comment]
In the meantime you can follow the docs recommended steps
https://docs.stake.tax/export-csv-formats/cointracking

Change your user time zone to UTC:
Account -> Account Settings -> Account & Notifications -> Your time zone -> set to UTC

**Comment by hodgerpodger** [comment]
Closing as I think it's just really prone to error vs. at least there's a good path for users if inclined.
