### ISSUE TITLE
LUNA: Wallet address not found

### ISSUE THREAD

**Issue by kickthedragon** [hodgerpodger/staketaxcsv#73]
I keep getting this error where LUNA wallet address is not found, even though I know for sure that I am copying and pasting the correct LUNA address.  I also know for sure transactions have transpired on this address.

![image](https://user-images.githubusercontent.com/5422123/155604236-f83865d7-1dcf-457b-824f-1330727fc0ab.png)

**Comment by hodgerpodger** [comment]
Oi okay.  This is probably tough to debug without the address.  If willing, can you DM twitter @staketax or send email to support@stake.tax?

**Comment by kickthedragon** [comment]
It actually seems to have resolved itself.  Very strange.  Perhaps it was a caching situation form the explorer itself?  

Regardless thank you for the quick response!

**Comment by hodgerpodger** [comment]
Nice!  Maybe a temporal issue with data provider.  I'll see if there's a better message when that happens.  thanks for reporting nonetheless
