### ISSUE TITLE
Not recognizing wormhole wrapped asset LP on Terra

### ISSUE THREAD

**Issue by wengzilla** [hodgerpodger/staketaxcsv#74]
[wsstSOL](https://finder.extraterrestrial.money/mainnet/address/terra1t9ul45l7m6jw6sxgvnp8e5hj8xzkjsg82g84ap)

Sample transaction: [BF9FA710C172B5C41C4460EB80CA4BAC171B6FE363FADFEA7DB48DFB5A015C76](https://finder.extraterrestrial.money/mainnet/tx/BF9FA710C172B5C41C4460EB80CA4BAC171B6FE363FADFEA7DB48DFB5A015C76)

Code that currently decodes LP relies on field "symbol" in the init_msg, but here it seems to be blank (e.g., "").

**Comment by hodgerpodger** [comment]
Just removing issues for which action unlikely to be taken.  Re-add if desired.
