### ISSUE TITLE
UST/BLUNA Swaps on Astroport are missing cost basis 

### ISSUE THREAD

**Issue by AGBULLBEAR** [hodgerpodger/staketaxcsv#79]
Really appreciate the work you do and I plan on making a generous donation. Just wanted to point out an issue when purchasing UST/bLUNA on astroport that seems to pull in no cost basis when importing CSV into Zenledger. Thanks!

**Comment by hodgerpodger** [comment]
Guessing this is probably related to Zenledger or import process.  In any case, probably not enough detail to be actionable.  Re-open if desired.
