### ISSUE TITLE
3 SOL transaction types (_STAKING_DELEGATE, _STAKING_DEACTIVATE, _STAKING_WITHDRAW) not included in Koinly CSV

### ISSUE THREAD

**Issue by Eldaw** [hodgerpodger/staketaxcsv#80]
SOL transactions that only have a fee (i.e. no transfer amount) don't get included in the exported CSV for Koinly. For example, none of these transactions appear in the CSV even though a fee was paid on each of them:

_STAKING_DELEGATE
_STAKING_DEACTIVATE
_STAKING_WITHDRAW

As a result, it is necessary to manually add 'Cost' transactions in Koinly to take these transactions into account.

To clarify: these transactions do appear in the web GUI when viewing the output after analysing the SOL address, but they are not included in the exported CSV file.

**Comment by Eldaw** [comment]
In case it helps: an easy way to generate these transactions is to use Exodus wallet to stake your SOL and then unstake it.

**Comment by hodgerpodger** [comment]
Thanks for patience and persistence.  Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/644ad80b3f2fa9073bf9d6a7886e8d7ab0e786d4.  Reopen if continued or related issues.
