### ISSUE TITLE
Osmosis LP Rewards not showing up in report after v7 Carbon upgrade

### ISSUE THREAD

**Issue by cryptoYJ** [hodgerpodger/staketaxcsv#81]
Osmosis lp rewards not working after v7 Carbon upgrade.  Swap transactions work properly.

**Comment by nicholaswiseman** [comment]
I haven't seen anything LP rewards since Feb 28. Looks like the issue is on API side. Not sure who knows next steps.

**Comment by hodgerpodger** [comment]
Ah, I've notified the data providers. They've let me know they are aware and will resolve in due time when more important matters are handled first.

**Comment by nicholaswiseman** [comment]
Fantastic! Thank you

**Comment by cccassidy** [comment]
Looks like they are back, I see rewards through the 4th.

**Comment by hodgerpodger** [comment]
Nice, spot checked a few addresses and see rewards updated now.  Re-open if any folks continue to see the issue if generating a CSV after 3/5/22.
