### ISSUE TITLE
Duplicate fees in Cointracking.info format

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#86]
Cointracking.info output fees are duplicated when fees are in third currency.

As we have discussed (https://github.com/hodgerpodger/staketaxcsv/issues/31) cointracking.info requires fees in third currency to be on their own separate transaction. 

But here they are in the trade line and also in the "other fee" line. 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/20350385/156911679-6963e7d3-7270-4ec0-8e06-ce01fe555d04.png">

This causes the that the fee report in cointracking counts twice this fee

**Comment by hodgerpodger** [comment]
hm i'm not really following--seems like this is the "good" version

**Comment by Mylros** [comment]
On the first line, there is a fee (0.367735 UST), the same fee is also on the second line ("other fee")
this causes the fee to be "counted" twice in some reports in cointracking.info.

In this case, it should only show the fee on the second line. The first line fee is redundant.

**Comment by hodgerpodger** [comment]
My understanding is that the fee column is disregarded in cointracking, as described in https://github.com/hodgerpodger/staketaxcsv/issues/31.  So the danger is not double counting but undercounting?  Perhaps I'm not seeing the issue fully.

**Comment by hodgerpodger** [comment]
Looking at https://cointracking.freshdesk.com/en/support/solutions/articles/29000007202-entering-fees again, I think this is consistent with the description?

![screen2](https://user-images.githubusercontent.com/2503441/156918504-3c4cb196-b42c-410f-b8e6-0aa913740bce.png)

I haven't gone totally in depth in cointracking, so perhaps my original understanding is incorrect.

**Comment by hodgerpodger** [comment]
Closing issue.  Reopen if disagreement.
