### ISSUE TITLE
Cointracking.info token symbols

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#90]
Cointracking.info uses their own naming format for some tokens to distinguish them from other equally named tokens

For example LUNA is LUNA2 

These are other Terra tokens I've found
PSI should be PSI2
MINE should be MINE2
MIR should be MIR2
ASTRO should be ASTRO5
PRISM should be  PRISM3
WHALE should be WHALE3

I'll update this list when I find more

**Comment by hodgerpodger** [comment]
Awesome, thanks for doing this work.  I'll make this change late tomorrow as it's a quickie.

**Comment by hodgerpodger** [comment]
Fixed and deployed. 

https://github.com/hodgerpodger/staketaxcsv/commit/35e02e9590a2585efe002051966c4970c3892594.

Feel free to reopen/create new github issue for more required tokens.
