### ISSUE TITLE
Koinly STARS not loading correctly

### ISSUE THREAD

**Issue by cccassidy** [hodgerpodger/staketaxcsv#93]
Koinly defaults the 'STARS' currency to some other token not the 'Stargaze' token on Osmosis.  I was able to override this by setting the currency to `ID:36899` in the CSV for import.  It seems that tells it to use the Koinly internal ID: https://app.koinly.io/p/markets/36899

Not a huge deal to search/replace but figured it might be able to added like you did with the GAMM->NULL switch.  Thanks!

**Comment by hodgerpodger** [comment]
Fixed and deployed. 

https://github.com/hodgerpodger/staketaxcsv/commit/35e02e9590a2585efe002051966c4970c3892594.

Feel free to reopen/create new github issue for more required tokens.

**Comment by git-rocky** [comment]
Mine (Terra) ID is 21256
When I import CSV into Koinly, it shows SpaceMine 21257 instead.

**Comment by hodgerpodger** [comment]
Fixed and deployed MINE issue with https://github.com/hodgerpodger/staketaxcsv/commit/44e8337956c142b6946bd868d2e6e1c6f86d0d01

**Comment by mbolesta** [comment]
This seems to have broken for STARS again. Manually updating the CSV to ID:36899 fixes it.

**Comment by hodgerpodger** [comment]
thanks for the heads up!  Will fix tomorrow

**Comment by hodgerpodger** [comment]
Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/6c58fbf19013f0a70d676a6defccd1b9abcc3dbb

**Comment by mbolesta** [comment]
ARCH 3189

When I import CSV into Koinly, it shows Archimedes Finance 1883 instead.

**Comment by hodgerpodger** [comment]
Thanks for reporting.  Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/ec86c29b15b4f69ce687f945f36b4b5d93d4d1b2 .

**Comment by terra-moonshot** [comment]
unknown_cw20:terra1lxx40s29qvkrcj8fsa3yzyehy7w50umdvvnls2r830rys6lu2zns63eelv ID:16962317
unknown_erc20/0xAE6D3334989a22A65228732446731438672418F2 ID:19886237

**Comment by hodgerpodger** [comment]
Thanks for reporting.  Fixed and deployed with https://github.com/hodgerpodger/staketaxcsv/commit/9746c6a12e116744e67da9b00f7aa023ee760e39 .

**Comment by terra-moonshot** [comment]
unknown_factory/kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7/uusk ID:10392240

**Comment by milldavid2000** [comment]
Just downloaded my Coreum transactions. Koinly has them showing as CORE DAO id 121. I would like to request it be updated to Coreum id 486. 

Also, I cannot seem to find the currency ID in the CSV to do the manual update.
Any help is much appreciated!

**Comment by hodgerpodger** [comment]
Thanks for reporting @milldavid2000 .  Fixed and deployed with 27082351a01624c6e59773edeac89ffba02647c3 .

It's live on website but you can also edit the CSV via search and replace: CORE -> ID:68700
