### ISSUE TITLE
ALGO: Group transactions missing

### ISSUE THREAD

**Issue by cccassidy** [hodgerpodger/staketaxcsv#95]
Looks like group transactions w/ ASAs aren't showing in the CSV output.  I see a line in the web output with a tx type of "_UNKNOWN". 
 A sample tx here is from the HDL airdrop:  https://algoexplorer.io/tx/group/RkVInzt9QKqxHXbiSfctbTNoZ5grLR1zkK7uNrPFOhs%3D.

**Comment by jumperavocado** [comment]
Thanks for the report! I'll fix it asap

**Comment by hodgerpodger** [comment]
Fix deployed.

https://github.com/hodgerpodger/staketaxcsv/commit/d69c1ea851ba11897047f7d7adad7b883907e387

**Comment by cccassidy** [comment]
Looks good thanks again!
