### ISSUE TITLE
Request to Add Support for CRO 

### ISSUE THREAD

**Issue by aw126** [hodgerpodger/staketaxcsv#96]
The project is awesome and solves people's pain points for crypto taxation. 

As one of the top 20 projects in the space, there have been demanding requests for CSVs request for Cronos (CRO). It would be great if you can add support for CROs in your project: https://crypto.org/. Thank you.

**Comment by hendrickson02** [comment]
Are you specifically referring to Cronos Chain (the ETH sidechain), or Crypto.org chain?

**Comment by aw126** [comment]
> Are you specifically referring to Cronos Chain (the ETH sidechain), or Crypto.org chain?



> Are you specifically referring to Cronos Chain (the ETH sidechain), or Crypto.org chain?

Crypto.org chain, thanks.

**Comment by aw126** [comment]
> Are you specifically referring to Cronos Chain (the ETH sidechain), or Crypto.org chain?



> Are you specifically referring to Cronos Chain (the ETH sidechain), or Crypto.org chain?

Crypto.org chain, thanks.

**Comment by dorian-coygo** [comment]
would love to see this as well :)

**Comment by bigshooTer39** [comment]
Someone has already built a csv export tool for crypto.org chain.   I've been using it for about a year and still use it all the time.  Just pop in your address and download.  Here's the link 

http://crypto.barkisoft.de/

Tagging you guys.   @dorian-coygo @aw126 @

**Comment by aw126** [comment]
> Someone has already built a csv export tool for crypto.org chain. I've been using it for about a year and still use it all the time. Just pop in your address and download. Here's the link
> 
> http://crypto.barkisoft.de/
> 
> Tagging you guys. @dorian-coygo @aw126 @

It looks like it connects to Koinly, will check it out, thanks for sharing it!

**Comment by hodgerpodger** [comment]
closing due to old request.  reopen if desired.
