### ISSUE TITLE
Sifchain DEX support request

### ISSUE THREAD

**Issue by arno01** [hodgerpodger/staketaxcsv#97]
Sifchain DEX official page https://dex.sifchain.finance
Page ran by the community https://sifchain.akash.pro

**Comment by wengzilla** [comment]
For future reference, the API endpoint is as follows: https://api.sifchain.finance/txs?message.sender=<send_address>

**Comment by pjm200** [comment]
It would be useful if stake.tax could work with Sifchain.

I would be grateful if you could prioritize this feature, and I must say I am very impressed with the quality of the tool you have developed so far.

I am grateful to stake.tax and have donated to you.

**Comment by hodgerpodger** [comment]
@wengzilla oops didn't see your comment until now.

I'd say juno and stars folders are probably examples that work.

**Comment by milwik63** [comment]
Another vote/request for Sifchain/ROWAN.  Thanks!!!

**Comment by hodgerpodger** [comment]
closing due to old request.  ROWAN implementation actually in codebase but I was unable to find a node with useful enough history.
